const grid_mapper = {
    rows: {
        template: {
            regex_pattern: '^grid-(rows-)?([0-9]+)?(\\w+)?$',
            values: [
                { id: 1, text: '1', value: 'grid-rows-1' },
                { id: 2, text: '2', value: 'grid-rows-2'},
                { id: 3, text: '3', value: 'grid-rows-3'},
                { id: 4, text: '4', value: 'grid-rows-4'},
                { id: 5, text: '5', value: 'grid-rows-5'},
                { id: 6, text: '6', value: 'grid-rows-6'},
                { id: 7, text: 'none', value: 'grid-rows-none'},
            ],
        },
        gap: {
            regex_pattern: 'gap-(y-)?[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'gap-y-0' },
                { id: 2, text: '0.5', value: 'gap-y-0.5'},
                { id: 3, text: '1', value: 'gap-y-1'},
                { id: 4, text: '1.5', value: 'gap-y-1.5'},
                { id: 5, text: '2', value: 'gap-y-2'},
                { id: 6, text: '2.5', value: 'gap-y-2.5'},
                { id: 7, text: '3', value: 'gap-y-3'},
                { id: 8, text: '3.5', value: 'gap-y-3.5'},
                { id: 9, text: '4', value: 'gap-y-4'},
                { id: 10, text: '5', value: 'gap-y-5'},
                { id: 11, text: '6', value: 'gap-y-6'},
                { id: 12, text: '7', value: 'gap-y-7'},
                { id: 13, text: '8', value: 'gap-y-8'},
                { id: 14, text: '9', value: 'gap-y-9'},
                { id: 15, text: '10', value: 'gap-y-10'},
                { id: 16, text: '11', value: 'gap-y-11'},
                { id: 17, text: '12', value: 'gap-y-12'},
                { id: 18, text: '14', value: 'gap-y-14'},
                { id: 19, text: '16', value: 'gap-y-16'},
                { id: 20, text: '20', value: 'gap-y-20'},
                { id: 21, text: '24', value: 'gap-y-24'},
                { id: 22, text: '28', value: 'gap-y-28'},
                { id: 23, text: '32', value: 'gap-y-32'},
                { id: 24, text: '36', value: 'gap-y-36'},
                { id: 25, text: '40', value: 'gap-y-40'},
                { id: 26, text: '44', value: 'gap-y-44'},
                { id: 27, text: '48', value: 'gap-y-48'},
                { id: 28, text: '52', value: 'gap-y-52'},
                { id: 29, text: '56', value: 'gap-y-56'},
                { id: 30, text: '60', value: 'gap-y-60'},
                { id: 31, text: '64', value: 'gap-y-64'},
                { id: 32, text: '72', value: 'gap-y-72'},
                { id: 33, text: '80', value: 'gap-y-80'},
                { id: 34, text: '96', value: 'gap-y-96'},
            ],
        }
    },
    cols: {
        template: {
            regex_pattern: '^grid-(cols-)?([0-9]+)?(\\w+)?$',
            values: [
                { id: 1, text: '1', value: 'grid-cols-1' },
                { id: 2, text: '2', value: 'grid-cols-2'},
                { id: 3, text: '3', value: 'grid-cols-3'},
                { id: 4, text: '4', value: 'grid-cols-4'},
                { id: 5, text: '5', value: 'grid-cols-5'},
                { id: 6, text: '6', value: 'grid-cols-6'},
                { id: 7, text: '7', value: 'grid-cols-7'},
                { id: 8, text: '8', value: 'grid-cols-8'},
                { id: 9, text: '9', value: 'grid-cols-9'},
                { id: 10, text: '10', value: 'grid-cols-10'},
                { id: 11, text: '11', value: 'grid-cols-11'},
                { id: 12, text: '12', value: 'grid-cols-12'},
                { id: 13, text: 'none', value: 'grid-cols-none'},
            ],
        },
        gap: {
            regex_pattern: 'gap-(x-)?[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'gap-x-0' },
                { id: 2, text: '0.5', value: 'gap-x-0.5'},
                { id: 3, text: '1', value: 'gap-x-1'},
                { id: 4, text: '1.5', value: 'gap-x-1.5'},
                { id: 5, text: '2', value: 'gap-x-2'},
                { id: 6, text: '2.5', value: 'gap-x-2.5'},
                { id: 7, text: '3', value: 'gap-x-3'},
                { id: 8, text: '3.5', value: 'gap-x-3.5'},
                { id: 9, text: '4', value: 'gap-x-4'},
                { id: 10, text: '5', value: 'gap-x-5'},
                { id: 11, text: '6', value: 'gap-x-6'},
                { id: 12, text: '7', value: 'gap-x-7'},
                { id: 13, text: '8', value: 'gap-x-8'},
                { id: 14, text: '9', value: 'gap-x-9'},
                { id: 15, text: '10', value: 'gap-x-10'},
                { id: 16, text: '11', value: 'gap-x-11'},
                { id: 17, text: '12', value: 'gap-x-12'},
                { id: 18, text: '14', value: 'gap-x-14'},
                { id: 19, text: '16', value: 'gap-x-16'},
                { id: 20, text: '20', value: 'gap-x-20'},
                { id: 21, text: '24', value: 'gap-x-24'},
                { id: 22, text: '28', value: 'gap-x-28'},
                { id: 23, text: '32', value: 'gap-x-32'},
                { id: 24, text: '36', value: 'gap-x-36'},
                { id: 25, text: '40', value: 'gap-x-40'},
                { id: 26, text: '44', value: 'gap-x-44'},
                { id: 27, text: '48', value: 'gap-x-48'},
                { id: 28, text: '52', value: 'gap-x-52'},
                { id: 29, text: '56', value: 'gap-x-56'},
                { id: 30, text: '60', value: 'gap-x-60'},
                { id: 31, text: '64', value: 'gap-x-64'},
                { id: 32, text: '72', value: 'gap-x-72'},
                { id: 33, text: '80', value: 'gap-x-80'},
                { id: 34, text: '96', value: 'gap-x-96'},
            ]
        }
    }
};

const flex_mapper = {
    gap: {
        regex_pattern: 'gap-(x-)?[0-9]+(\.[0-9])?',
        values: [
            { id: 1, text: '0', value: 'gap-x-0' },
            { id: 2, text: '0.5', value: 'gap-x-0.5'},
            { id: 3, text: '1', value: 'gap-x-1'},
            { id: 4, text: '1.5', value: 'gap-x-1.5'},
            { id: 5, text: '2', value: 'gap-x-2'},
            { id: 6, text: '2.5', value: 'gap-x-2.5'},
            { id: 7, text: '3', value: 'gap-x-3'},
            { id: 8, text: '3.5', value: 'gap-x-3.5'},
            { id: 9, text: '4', value: 'gap-x-4'},
            { id: 10, text: '5', value: 'gap-x-5'},
            { id: 11, text: '6', value: 'gap-x-6'},
            { id: 12, text: '7', value: 'gap-x-7'},
            { id: 13, text: '8', value: 'gap-x-8'},
            { id: 14, text: '9', value: 'gap-x-9'},
            { id: 15, text: '10', value: 'gap-x-10'},
            { id: 16, text: '11', value: 'gap-x-11'},
            { id: 17, text: '12', value: 'gap-x-12'},
            { id: 18, text: '14', value: 'gap-x-14'},
            { id: 19, text: '16', value: 'gap-x-16'},
            { id: 20, text: '20', value: 'gap-x-20'},
            { id: 21, text: '24', value: 'gap-x-24'},
            { id: 22, text: '28', value: 'gap-x-28'},
            { id: 23, text: '32', value: 'gap-x-32'},
            { id: 24, text: '36', value: 'gap-x-36'},
            { id: 25, text: '40', value: 'gap-x-40'},
            { id: 26, text: '44', value: 'gap-x-44'},
            { id: 27, text: '48', value: 'gap-x-48'},
            { id: 28, text: '52', value: 'gap-x-52'},
            { id: 29, text: '56', value: 'gap-x-56'},
            { id: 30, text: '60', value: 'gap-x-60'},
            { id: 31, text: '64', value: 'gap-x-64'},
            { id: 32, text: '72', value: 'gap-x-72'},
            { id: 33, text: '80', value: 'gap-x-80'},
            { id: 34, text: '96', value: 'gap-x-96'},
        ]
    }
};

export { grid_mapper, flex_mapper }
