const grid_mapper = {
    rows: {
        template: {
            regex_pattern: '^grid-(rows-)?([0-9]+)?(\\w+)?$',
            values: [
                { id: 1, text: '1', value: 'grid-rows-1' },
                { id: 2, text: '2', value: 'grid-rows-2'},
                { id: 3, text: '3', value: 'grid-rows-3'},
                { id: 4, text: '4', value: 'grid-rows-4'},
                { id: 5, text: '5', value: 'grid-rows-5'},
                { id: 6, text: '6', value: 'grid-rows-6'},
                { id: 7, text: 'none', value: 'grid-rows-none'},
            ],
        },
        gap: {
            regex_pattern: 'gap-(y-)?[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'gap-y-0' },
                { id: 2, text: '0.5', value: 'gap-y-0.5'},
                { id: 3, text: '1', value: 'gap-y-1'},
                { id: 4, text: '1.5', value: 'gap-y-1.5'},
                { id: 5, text: '2', value: 'gap-y-2'},
                { id: 6, text: '2.5', value: 'gap-y-2.5'},
                { id: 7, text: '3', value: 'gap-y-3'},
                { id: 8, text: '3.5', value: 'gap-y-3.5'},
                { id: 9, text: '4', value: 'gap-y-4'},
                { id: 10, text: '5', value: 'gap-y-5'},
                { id: 11, text: '6', value: 'gap-y-6'},
                { id: 12, text: '7', value: 'gap-y-7'},
                { id: 13, text: '8', value: 'gap-y-8'},
                { id: 14, text: '9', value: 'gap-y-9'},
                { id: 15, text: '10', value: 'gap-y-10'},
                { id: 16, text: '11', value: 'gap-y-11'},
                { id: 17, text: '12', value: 'gap-y-12'},
                { id: 18, text: '14', value: 'gap-y-14'},
                { id: 19, text: '16', value: 'gap-y-16'},
                { id: 20, text: '20', value: 'gap-y-20'},
                { id: 21, text: '24', value: 'gap-y-24'},
                { id: 22, text: '28', value: 'gap-y-28'},
                { id: 23, text: '32', value: 'gap-y-32'},
                { id: 24, text: '36', value: 'gap-y-36'},
                { id: 25, text: '40', value: 'gap-y-40'},
                { id: 26, text: '44', value: 'gap-y-44'},
                { id: 27, text: '48', value: 'gap-y-48'},
                { id: 28, text: '52', value: 'gap-y-52'},
                { id: 29, text: '56', value: 'gap-y-56'},
                { id: 30, text: '60', value: 'gap-y-60'},
                { id: 31, text: '64', value: 'gap-y-64'},
                { id: 32, text: '72', value: 'gap-y-72'},
                { id: 33, text: '80', value: 'gap-y-80'},
                { id: 34, text: '96', value: 'gap-y-96'},
            ],
        }
    },
    cols: {
        template: {
            regex_pattern: '^grid-(cols-)?([0-9]+)?(\\w+)?$',
            values: [
                { id: 1, text: '1', value: 'grid-cols-1' },
                { id: 2, text: '2', value: 'grid-cols-2'},
                { id: 3, text: '3', value: 'grid-cols-3'},
                { id: 4, text: '4', value: 'grid-cols-4'},
                { id: 5, text: '5', value: 'grid-cols-5'},
                { id: 6, text: '6', value: 'grid-cols-6'},
                { id: 7, text: '7', value: 'grid-cols-7'},
                { id: 8, text: '8', value: 'grid-cols-8'},
                { id: 9, text: '9', value: 'grid-cols-9'},
                { id: 10, text: '10', value: 'grid-cols-10'},
                { id: 11, text: '11', value: 'grid-cols-11'},
                { id: 12, text: '12', value: 'grid-cols-12'},
                { id: 13, text: 'none', value: 'grid-cols-none'},
            ],
        },
        gap: {
            regex_pattern: 'gap-(x-)?[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'gap-x-0' },
                { id: 2, text: '0.5', value: 'gap-x-0.5'},
                { id: 3, text: '1', value: 'gap-x-1'},
                { id: 4, text: '1.5', value: 'gap-x-1.5'},
                { id: 5, text: '2', value: 'gap-x-2'},
                { id: 6, text: '2.5', value: 'gap-x-2.5'},
                { id: 7, text: '3', value: 'gap-x-3'},
                { id: 8, text: '3.5', value: 'gap-x-3.5'},
                { id: 9, text: '4', value: 'gap-x-4'},
                { id: 10, text: '5', value: 'gap-x-5'},
                { id: 11, text: '6', value: 'gap-x-6'},
                { id: 12, text: '7', value: 'gap-x-7'},
                { id: 13, text: '8', value: 'gap-x-8'},
                { id: 14, text: '9', value: 'gap-x-9'},
                { id: 15, text: '10', value: 'gap-x-10'},
                { id: 16, text: '11', value: 'gap-x-11'},
                { id: 17, text: '12', value: 'gap-x-12'},
                { id: 18, text: '14', value: 'gap-x-14'},
                { id: 19, text: '16', value: 'gap-x-16'},
                { id: 20, text: '20', value: 'gap-x-20'},
                { id: 21, text: '24', value: 'gap-x-24'},
                { id: 22, text: '28', value: 'gap-x-28'},
                { id: 23, text: '32', value: 'gap-x-32'},
                { id: 24, text: '36', value: 'gap-x-36'},
                { id: 25, text: '40', value: 'gap-x-40'},
                { id: 26, text: '44', value: 'gap-x-44'},
                { id: 27, text: '48', value: 'gap-x-48'},
                { id: 28, text: '52', value: 'gap-x-52'},
                { id: 29, text: '56', value: 'gap-x-56'},
                { id: 30, text: '60', value: 'gap-x-60'},
                { id: 31, text: '64', value: 'gap-x-64'},
                { id: 32, text: '72', value: 'gap-x-72'},
                { id: 33, text: '80', value: 'gap-x-80'},
                { id: 34, text: '96', value: 'gap-x-96'},
            ]
        }
    }
};

const flex_mapper = {
    gap: {
        regex_pattern: 'gap-(x-)?[0-9]+(\.[0-9])?',
        values: [
            { id: 1, text: '0', value: 'gap-x-0' },
            { id: 2, text: '0.5', value: 'gap-x-0.5'},
            { id: 3, text: '1', value: 'gap-x-1'},
            { id: 4, text: '1.5', value: 'gap-x-1.5'},
            { id: 5, text: '2', value: 'gap-x-2'},
            { id: 6, text: '2.5', value: 'gap-x-2.5'},
            { id: 7, text: '3', value: 'gap-x-3'},
            { id: 8, text: '3.5', value: 'gap-x-3.5'},
            { id: 9, text: '4', value: 'gap-x-4'},
            { id: 10, text: '5', value: 'gap-x-5'},
            { id: 11, text: '6', value: 'gap-x-6'},
            { id: 12, text: '7', value: 'gap-x-7'},
            { id: 13, text: '8', value: 'gap-x-8'},
            { id: 14, text: '9', value: 'gap-x-9'},
            { id: 15, text: '10', value: 'gap-x-10'},
            { id: 16, text: '11', value: 'gap-x-11'},
            { id: 17, text: '12', value: 'gap-x-12'},
            { id: 18, text: '14', value: 'gap-x-14'},
            { id: 19, text: '16', value: 'gap-x-16'},
            { id: 20, text: '20', value: 'gap-x-20'},
            { id: 21, text: '24', value: 'gap-x-24'},
            { id: 22, text: '28', value: 'gap-x-28'},
            { id: 23, text: '32', value: 'gap-x-32'},
            { id: 24, text: '36', value: 'gap-x-36'},
            { id: 25, text: '40', value: 'gap-x-40'},
            { id: 26, text: '44', value: 'gap-x-44'},
            { id: 27, text: '48', value: 'gap-x-48'},
            { id: 28, text: '52', value: 'gap-x-52'},
            { id: 29, text: '56', value: 'gap-x-56'},
            { id: 30, text: '60', value: 'gap-x-60'},
            { id: 31, text: '64', value: 'gap-x-64'},
            { id: 32, text: '72', value: 'gap-x-72'},
            { id: 33, text: '80', value: 'gap-x-80'},
            { id: 34, text: '96', value: 'gap-x-96'},
        ]
    }
};

const spacing_mapper = {
    padding: {
        all: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'p-0' },
                { id: 2, text: '0.5', value: 'p-0.5'},
                { id: 3, text: '1', value: 'p-1'},
                { id: 4, text: '1.5', value: 'p-1.5'},
                { id: 5, text: '2', value: 'p-2'},
                { id: 6, text: '2.5', value: 'p-2.5'},
                { id: 7, text: '3', value: 'p-3'},
                { id: 8, text: '3.5', value: 'p-3.5'},
                { id: 9, text: '4', value: 'p-4'},
                { id: 10, text: '5', value: 'p-5'},
                { id: 11, text: '6', value: 'p-6'},
                { id: 12, text: '7', value: 'p-7'},
                { id: 13, text: '8', value: 'p-8'},
                { id: 14, text: '9', value: 'p-9'},
                { id: 15, text: '10', value: 'p-10'},
                { id: 16, text: '11', value: 'p-11'},
                { id: 17, text: '12', value: 'p-12'},
                { id: 18, text: '14', value: 'p-14'},
                { id: 19, text: '16', value: 'p-16'},
                { id: 20, text: '20', value: 'p-20'},
                { id: 21, text: '24', value: 'p-24'},
                { id: 22, text: '28', value: 'p-28'},
                { id: 23, text: '32', value: 'p-32'},
                { id: 24, text: '36', value: 'p-36'},
                { id: 25, text: '40', value: 'p-40'},
                { id: 26, text: '44', value: 'p-44'},
                { id: 27, text: '48', value: 'p-48'},
                { id: 28, text: '52', value: 'p-52'},
                { id: 29, text: '56', value: 'p-56'},
                { id: 30, text: '60', value: 'p-60'},
                { id: 31, text: '64', value: 'p-64'},
                { id: 32, text: '72', value: 'p-72'},
                { id: 33, text: '80', value: 'p-80'},
                { id: 34, text: '96', value: 'p-96'},
            ]
        },
        vertical: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'py-0' },
                { id: 2, text: '0.5', value: 'py-0.5'},
                { id: 3, text: '1', value: 'py-1'},
                { id: 4, text: '1.5', value: 'py-1.5'},
                { id: 5, text: '2', value: 'py-2'},
                { id: 6, text: '2.5', value: 'py-2.5'},
                { id: 7, text: '3', value: 'py-3'},
                { id: 8, text: '3.5', value: 'py-3.5'},
                { id: 9, text: '4', value: 'py-4'},
                { id: 10, text: '5', value: 'py-5'},
                { id: 11, text: '6', value: 'py-6'},
                { id: 12, text: '7', value: 'py-7'},
                { id: 13, text: '8', value: 'py-8'},
                { id: 14, text: '9', value: 'py-9'},
                { id: 15, text: '10', value: 'py-10'},
                { id: 16, text: '11', value: 'py-11'},
                { id: 17, text: '12', value: 'py-12'},
                { id: 18, text: '14', value: 'py-14'},
                { id: 19, text: '16', value: 'py-16'},
                { id: 20, text: '20', value: 'py-20'},
                { id: 21, text: '24', value: 'py-24'},
                { id: 22, text: '28', value: 'py-28'},
                { id: 23, text: '32', value: 'py-32'},
                { id: 24, text: '36', value: 'py-36'},
                { id: 25, text: '40', value: 'py-40'},
                { id: 26, text: '44', value: 'py-44'},
                { id: 27, text: '48', value: 'py-48'},
                { id: 28, text: '52', value: 'py-52'},
                { id: 29, text: '56', value: 'py-56'},
                { id: 30, text: '60', value: 'py-60'},
                { id: 31, text: '64', value: 'py-64'},
                { id: 32, text: '72', value: 'py-72'},
                { id: 33, text: '80', value: 'py-80'},
                { id: 34, text: '96', value: 'py-96'},
            ]
        },
        horizontal: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'px-0' },
                { id: 2, text: '0.5', value: 'px-0.5'},
                { id: 3, text: '1', value: 'px-1'},
                { id: 4, text: '1.5', value: 'px-1.5'},
                { id: 5, text: '2', value: 'px-2'},
                { id: 6, text: '2.5', value: 'px-2.5'},
                { id: 7, text: '3', value: 'px-3'},
                { id: 8, text: '3.5', value: 'px-3.5'},
                { id: 9, text: '4', value: 'px-4'},
                { id: 10, text: '5', value: 'px-5'},
                { id: 11, text: '6', value: 'px-6'},
                { id: 12, text: '7', value: 'px-7'},
                { id: 13, text: '8', value: 'px-8'},
                { id: 14, text: '9', value: 'px-9'},
                { id: 15, text: '10', value: 'px-10'},
                { id: 16, text: '11', value: 'px-11'},
                { id: 17, text: '12', value: 'px-12'},
                { id: 18, text: '14', value: 'px-14'},
                { id: 19, text: '16', value: 'px-16'},
                { id: 20, text: '20', value: 'px-20'},
                { id: 21, text: '24', value: 'px-24'},
                { id: 22, text: '28', value: 'px-28'},
                { id: 23, text: '32', value: 'px-32'},
                { id: 24, text: '36', value: 'px-36'},
                { id: 25, text: '40', value: 'px-40'},
                { id: 26, text: '44', value: 'px-44'},
                { id: 27, text: '48', value: 'px-48'},
                { id: 28, text: '52', value: 'px-52'},
                { id: 29, text: '56', value: 'px-56'},
                { id: 30, text: '60', value: 'px-60'},
                { id: 31, text: '64', value: 'px-64'},
                { id: 32, text: '72', value: 'px-72'},
                { id: 33, text: '80', value: 'px-80'},
                { id: 34, text: '96', value: 'px-96'},
            ]
        },
        top: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'pt-0' },
                { id: 2, text: '0.5', value: 'pt-0.5'},
                { id: 3, text: '1', value: 'pt-1'},
                { id: 4, text: '1.5', value: 'pt-1.5'},
                { id: 5, text: '2', value: 'pt-2'},
                { id: 6, text: '2.5', value: 'pt-2.5'},
                { id: 7, text: '3', value: 'pt-3'},
                { id: 8, text: '3.5', value: 'pt-3.5'},
                { id: 9, text: '4', value: 'pt-4'},
                { id: 10, text: '5', value: 'pt-5'},
                { id: 11, text: '6', value: 'pt-6'},
                { id: 12, text: '7', value: 'pt-7'},
                { id: 13, text: '8', value: 'pt-8'},
                { id: 14, text: '9', value: 'pt-9'},
                { id: 15, text: '10', value: 'pt-10'},
                { id: 16, text: '11', value: 'pt-11'},
                { id: 17, text: '12', value: 'pt-12'},
                { id: 18, text: '14', value: 'pt-14'},
                { id: 19, text: '16', value: 'pt-16'},
                { id: 20, text: '20', value: 'pt-20'},
                { id: 21, text: '24', value: 'pt-24'},
                { id: 22, text: '28', value: 'pt-28'},
                { id: 23, text: '32', value: 'pt-32'},
                { id: 24, text: '36', value: 'pt-36'},
                { id: 25, text: '40', value: 'pt-40'},
                { id: 26, text: '44', value: 'pt-44'},
                { id: 27, text: '48', value: 'pt-48'},
                { id: 28, text: '52', value: 'pt-52'},
                { id: 29, text: '56', value: 'pt-56'},
                { id: 30, text: '60', value: 'pt-60'},
                { id: 31, text: '64', value: 'pt-64'},
                { id: 32, text: '72', value: 'pt-72'},
                { id: 33, text: '80', value: 'pt-80'},
                { id: 34, text: '96', value: 'pt-96'},
            ]
        },
        right: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'pr-0' },
                { id: 2, text: '0.5', value: 'pr-0.5'},
                { id: 3, text: '1', value: 'pr-1'},
                { id: 4, text: '1.5', value: 'pr-1.5'},
                { id: 5, text: '2', value: 'pr-2'},
                { id: 6, text: '2.5', value: 'pr-2.5'},
                { id: 7, text: '3', value: 'pr-3'},
                { id: 8, text: '3.5', value: 'pr-3.5'},
                { id: 9, text: '4', value: 'pr-4'},
                { id: 10, text: '5', value: 'pr-5'},
                { id: 11, text: '6', value: 'pr-6'},
                { id: 12, text: '7', value: 'pr-7'},
                { id: 13, text: '8', value: 'pr-8'},
                { id: 14, text: '9', value: 'pr-9'},
                { id: 15, text: '10', value: 'pr-10'},
                { id: 16, text: '11', value: 'pr-11'},
                { id: 17, text: '12', value: 'pr-12'},
                { id: 18, text: '14', value: 'pr-14'},
                { id: 19, text: '16', value: 'pr-16'},
                { id: 20, text: '20', value: 'pr-20'},
                { id: 21, text: '24', value: 'pr-24'},
                { id: 22, text: '28', value: 'pr-28'},
                { id: 23, text: '32', value: 'pr-32'},
                { id: 24, text: '36', value: 'pr-36'},
                { id: 25, text: '40', value: 'pr-40'},
                { id: 26, text: '44', value: 'pr-44'},
                { id: 27, text: '48', value: 'pr-48'},
                { id: 28, text: '52', value: 'pr-52'},
                { id: 29, text: '56', value: 'pr-56'},
                { id: 30, text: '60', value: 'pr-60'},
                { id: 31, text: '64', value: 'pr-64'},
                { id: 32, text: '72', value: 'pr-72'},
                { id: 33, text: '80', value: 'pr-80'},
                { id: 34, text: '96', value: 'pr-96'},
            ]
        },
        bottom: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'pb-0' },
                { id: 2, text: '0.5', value: 'pb-0.5'},
                { id: 3, text: '1', value: 'pb-1'},
                { id: 4, text: '1.5', value: 'pb-1.5'},
                { id: 5, text: '2', value: 'pb-2'},
                { id: 6, text: '2.5', value: 'pb-2.5'},
                { id: 7, text: '3', value: 'pb-3'},
                { id: 8, text: '3.5', value: 'pb-3.5'},
                { id: 9, text: '4', value: 'pb-4'},
                { id: 10, text: '5', value: 'pb-5'},
                { id: 11, text: '6', value: 'pb-6'},
                { id: 12, text: '7', value: 'pb-7'},
                { id: 13, text: '8', value: 'pb-8'},
                { id: 14, text: '9', value: 'pb-9'},
                { id: 15, text: '10', value: 'pb-10'},
                { id: 16, text: '11', value: 'pb-11'},
                { id: 17, text: '12', value: 'pb-12'},
                { id: 18, text: '14', value: 'pb-14'},
                { id: 19, text: '16', value: 'pb-16'},
                { id: 20, text: '20', value: 'pb-20'},
                { id: 21, text: '24', value: 'pb-24'},
                { id: 22, text: '28', value: 'pb-28'},
                { id: 23, text: '32', value: 'pb-32'},
                { id: 24, text: '36', value: 'pb-36'},
                { id: 25, text: '40', value: 'pb-40'},
                { id: 26, text: '44', value: 'pb-44'},
                { id: 27, text: '48', value: 'pb-48'},
                { id: 28, text: '52', value: 'pb-52'},
                { id: 29, text: '56', value: 'pb-56'},
                { id: 30, text: '60', value: 'pb-60'},
                { id: 31, text: '64', value: 'pb-64'},
                { id: 32, text: '72', value: 'pb-72'},
                { id: 33, text: '80', value: 'pb-80'},
                { id: 34, text: '96', value: 'pb-96'},
            ]
        },
        left: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'pl-0' },
                { id: 2, text: '0.5', value: 'pl-0.5'},
                { id: 3, text: '1', value: 'pl-1'},
                { id: 4, text: '1.5', value: 'pl-1.5'},
                { id: 5, text: '2', value: 'pl-2'},
                { id: 6, text: '2.5', value: 'pl-2.5'},
                { id: 7, text: '3', value: 'pl-3'},
                { id: 8, text: '3.5', value: 'pl-3.5'},
                { id: 9, text: '4', value: 'pl-4'},
                { id: 10, text: '5', value: 'pl-5'},
                { id: 11, text: '6', value: 'pl-6'},
                { id: 12, text: '7', value: 'pl-7'},
                { id: 13, text: '8', value: 'pl-8'},
                { id: 14, text: '9', value: 'pl-9'},
                { id: 15, text: '10', value: 'pl-10'},
                { id: 16, text: '11', value: 'pl-11'},
                { id: 17, text: '12', value: 'pl-12'},
                { id: 18, text: '14', value: 'pl-14'},
                { id: 19, text: '16', value: 'pl-16'},
                { id: 20, text: '20', value: 'pl-20'},
                { id: 21, text: '24', value: 'pl-24'},
                { id: 22, text: '28', value: 'pl-28'},
                { id: 23, text: '32', value: 'pl-32'},
                { id: 24, text: '36', value: 'pl-36'},
                { id: 25, text: '40', value: 'pl-40'},
                { id: 26, text: '44', value: 'pl-44'},
                { id: 27, text: '48', value: 'pl-48'},
                { id: 28, text: '52', value: 'pl-52'},
                { id: 29, text: '56', value: 'pl-56'},
                { id: 30, text: '60', value: 'pl-60'},
                { id: 31, text: '64', value: 'pl-64'},
                { id: 32, text: '72', value: 'pl-72'},
                { id: 33, text: '80', value: 'pl-80'},
                { id: 34, text: '96', value: 'pl-96'},
            ]
        }
    },
    margin: {
        all: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'm-0' },
                { id: 2, text: '0.5', value: 'm-0.5'},
                { id: 3, text: '1', value: 'm-1'},
                { id: 4, text: '1.5', value: 'm-1.5'},
                { id: 5, text: '2', value: 'm-2'},
                { id: 6, text: '2.5', value: 'm-2.5'},
                { id: 7, text: '3', value: 'm-3'},
                { id: 8, text: '3.5', value: 'm-3.5'},
                { id: 9, text: '4', value: 'm-4'},
                { id: 10, text: '5', value: 'm-5'},
                { id: 11, text: '6', value: 'm-6'},
                { id: 12, text: '7', value: 'm-7'},
                { id: 13, text: '8', value: 'm-8'},
                { id: 14, text: '9', value: 'm-9'},
                { id: 15, text: '10', value: 'm-10'},
                { id: 16, text: '11', value: 'm-11'},
                { id: 17, text: '12', value: 'm-12'},
                { id: 18, text: '14', value: 'm-14'},
                { id: 19, text: '16', value: 'm-16'},
                { id: 20, text: '20', value: 'm-20'},
                { id: 21, text: '24', value: 'm-24'},
                { id: 22, text: '28', value: 'm-28'},
                { id: 23, text: '32', value: 'm-32'},
                { id: 24, text: '36', value: 'm-36'},
                { id: 25, text: '40', value: 'm-40'},
                { id: 26, text: '44', value: 'm-44'},
                { id: 27, text: '48', value: 'm-48'},
                { id: 28, text: '52', value: 'm-52'},
                { id: 29, text: '56', value: 'm-56'},
                { id: 30, text: '60', value: 'm-60'},
                { id: 31, text: '64', value: 'm-64'},
                { id: 32, text: '72', value: 'm-72'},
                { id: 33, text: '80', value: 'm-80'},
                { id: 34, text: '96', value: 'm-96'},
                { id: 35, text: '-0', value: '-m-0' },
                { id: 36, text: '-0.5', value: '-m-0.5'},
                { id: 37, text: '-1', value: '-m-1'},
                { id: 38, text: '-1.5', value: '-m-1.5'},
                { id: 39, text: '-2', value: '-m-2'},
                { id: 40, text: '-2.5', value: '-m-2.5'},
                { id: 41, text: '-3', value: '-m-3'},
                { id: 42, text: '-3.5', value: '-m-3.5'},
                { id: 43, text: '-4', value: '-m-4'},
                { id: 44, text: '-5', value: '-m-5'},
                { id: 45, text: '-6', value: '-m-6'},
                { id: 46, text: '-7', value: '-m-7'},
                { id: 47, text: '-8', value: '-m-8'},
                { id: 48, text: '-9', value: '-m-9'},
                { id: 49, text: '-10', value: '-m-10'},
                { id: 50, text: '-11', value: '-m-11'},
                { id: 51, text: '-12', value: '-m-12'},
                { id: 52, text: '-14', value: '-m-14'},
                { id: 53, text: '-16', value: '-m-16'},
                { id: 54, text: '-20', value: '-m-20'},
                { id: 55, text: '-24', value: '-m-24'},
                { id: 56, text: '-28', value: '-m-28'},
                { id: 57, text: '-32', value: '-m-32'},
                { id: 58, text: '-36', value: '-m-36'},
                { id: 59, text: '-40', value: '-m-40'},
                { id: 60, text: '-44', value: '-m-44'},
                { id: 61, text: '-48', value: '-m-48'},
                { id: 62, text: '-52', value: '-m-52'},
                { id: 63, text: '-56', value: '-m-56'},
                { id: 64, text: '-60', value: '-m-60'},
                { id: 65, text: '-64', value: '-m-64'},
                { id: 66, text: '-72', value: '-m-72'},
                { id: 67, text: '-80', value: '-m-80'},
                { id: 68, text: '-96', value: '-m-96'},
            ]
        },
        vertical: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'my-0' },
                { id: 2, text: '0.5', value: 'my-0.5'},
                { id: 3, text: '1', value: 'my-1'},
                { id: 4, text: '1.5', value: 'my-1.5'},
                { id: 5, text: '2', value: 'my-2'},
                { id: 6, text: '2.5', value: 'my-2.5'},
                { id: 7, text: '3', value: 'my-3'},
                { id: 8, text: '3.5', value: 'my-3.5'},
                { id: 9, text: '4', value: 'my-4'},
                { id: 10, text: '5', value: 'my-5'},
                { id: 11, text: '6', value: 'my-6'},
                { id: 12, text: '7', value: 'my-7'},
                { id: 13, text: '8', value: 'my-8'},
                { id: 14, text: '9', value: 'my-9'},
                { id: 15, text: '10', value: 'my-10'},
                { id: 16, text: '11', value: 'my-11'},
                { id: 17, text: '12', value: 'my-12'},
                { id: 18, text: '14', value: 'my-14'},
                { id: 19, text: '16', value: 'my-16'},
                { id: 20, text: '20', value: 'my-20'},
                { id: 21, text: '24', value: 'my-24'},
                { id: 22, text: '28', value: 'my-28'},
                { id: 23, text: '32', value: 'my-32'},
                { id: 24, text: '36', value: 'my-36'},
                { id: 25, text: '40', value: 'my-40'},
                { id: 26, text: '44', value: 'my-44'},
                { id: 27, text: '48', value: 'my-48'},
                { id: 28, text: '52', value: 'my-52'},
                { id: 29, text: '56', value: 'my-56'},
                { id: 30, text: '60', value: 'my-60'},
                { id: 31, text: '64', value: 'my-64'},
                { id: 32, text: '72', value: 'my-72'},
                { id: 33, text: '80', value: 'my-80'},
                { id: 34, text: '96', value: 'my-96'},
            ]
        },
        horizontal: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'mx-0' },
                { id: 2, text: '0.5', value: 'mx-0.5'},
                { id: 3, text: '1', value: 'mx-1'},
                { id: 4, text: '1.5', value: 'mx-1.5'},
                { id: 5, text: '2', value: 'mx-2'},
                { id: 6, text: '2.5', value: 'mx-2.5'},
                { id: 7, text: '3', value: 'mx-3'},
                { id: 8, text: '3.5', value: 'mx-3.5'},
                { id: 9, text: '4', value: 'mx-4'},
                { id: 10, text: '5', value: 'mx-5'},
                { id: 11, text: '6', value: 'mx-6'},
                { id: 12, text: '7', value: 'mx-7'},
                { id: 13, text: '8', value: 'mx-8'},
                { id: 14, text: '9', value: 'mx-9'},
                { id: 15, text: '10', value: 'mx-10'},
                { id: 16, text: '11', value: 'mx-11'},
                { id: 17, text: '12', value: 'mx-12'},
                { id: 18, text: '14', value: 'mx-14'},
                { id: 19, text: '16', value: 'mx-16'},
                { id: 20, text: '20', value: 'mx-20'},
                { id: 21, text: '24', value: 'mx-24'},
                { id: 22, text: '28', value: 'mx-28'},
                { id: 23, text: '32', value: 'mx-32'},
                { id: 24, text: '36', value: 'mx-36'},
                { id: 25, text: '40', value: 'mx-40'},
                { id: 26, text: '44', value: 'mx-44'},
                { id: 27, text: '48', value: 'mx-48'},
                { id: 28, text: '52', value: 'mx-52'},
                { id: 29, text: '56', value: 'mx-56'},
                { id: 30, text: '60', value: 'mx-60'},
                { id: 31, text: '64', value: 'mx-64'},
                { id: 32, text: '72', value: 'mx-72'},
                { id: 33, text: '80', value: 'mx-80'},
                { id: 34, text: '96', value: 'mx-96'},
            ]
        },
        top: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'mt-0' },
                { id: 2, text: '0.5', value: 'mt-0.5'},
                { id: 3, text: '1', value: 'mt-1'},
                { id: 4, text: '1.5', value: 'mt-1.5'},
                { id: 5, text: '2', value: 'mt-2'},
                { id: 6, text: '2.5', value: 'mt-2.5'},
                { id: 7, text: '3', value: 'mt-3'},
                { id: 8, text: '3.5', value: 'mt-3.5'},
                { id: 9, text: '4', value: 'mt-4'},
                { id: 10, text: '5', value: 'mt-5'},
                { id: 11, text: '6', value: 'mt-6'},
                { id: 12, text: '7', value: 'mt-7'},
                { id: 13, text: '8', value: 'mt-8'},
                { id: 14, text: '9', value: 'mt-9'},
                { id: 15, text: '10', value: 'mt-10'},
                { id: 16, text: '11', value: 'mt-11'},
                { id: 17, text: '12', value: 'mt-12'},
                { id: 18, text: '14', value: 'mt-14'},
                { id: 19, text: '16', value: 'mt-16'},
                { id: 20, text: '20', value: 'mt-20'},
                { id: 21, text: '24', value: 'mt-24'},
                { id: 22, text: '28', value: 'mt-28'},
                { id: 23, text: '32', value: 'mt-32'},
                { id: 24, text: '36', value: 'mt-36'},
                { id: 25, text: '40', value: 'mt-40'},
                { id: 26, text: '44', value: 'mt-44'},
                { id: 27, text: '48', value: 'mt-48'},
                { id: 28, text: '52', value: 'mt-52'},
                { id: 29, text: '56', value: 'mt-56'},
                { id: 30, text: '60', value: 'mt-60'},
                { id: 31, text: '64', value: 'mt-64'},
                { id: 32, text: '72', value: 'mt-72'},
                { id: 33, text: '80', value: 'mt-80'},
                { id: 34, text: '96', value: 'mt-96'},
            ]
        },
        right: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'mr-0' },
                { id: 2, text: '0.5', value: 'mr-0.5'},
                { id: 3, text: '1', value: 'mr-1'},
                { id: 4, text: '1.5', value: 'mr-1.5'},
                { id: 5, text: '2', value: 'mr-2'},
                { id: 6, text: '2.5', value: 'mr-2.5'},
                { id: 7, text: '3', value: 'mr-3'},
                { id: 8, text: '3.5', value: 'mr-3.5'},
                { id: 9, text: '4', value: 'mr-4'},
                { id: 10, text: '5', value: 'mr-5'},
                { id: 11, text: '6', value: 'mr-6'},
                { id: 12, text: '7', value: 'mr-7'},
                { id: 13, text: '8', value: 'mr-8'},
                { id: 14, text: '9', value: 'mr-9'},
                { id: 15, text: '10', value: 'mr-10'},
                { id: 16, text: '11', value: 'mr-11'},
                { id: 17, text: '12', value: 'mr-12'},
                { id: 18, text: '14', value: 'mr-14'},
                { id: 19, text: '16', value: 'mr-16'},
                { id: 20, text: '20', value: 'mr-20'},
                { id: 21, text: '24', value: 'mr-24'},
                { id: 22, text: '28', value: 'mr-28'},
                { id: 23, text: '32', value: 'mr-32'},
                { id: 24, text: '36', value: 'mr-36'},
                { id: 25, text: '40', value: 'mr-40'},
                { id: 26, text: '44', value: 'mr-44'},
                { id: 27, text: '48', value: 'mr-48'},
                { id: 28, text: '52', value: 'mr-52'},
                { id: 29, text: '56', value: 'mr-56'},
                { id: 30, text: '60', value: 'mr-60'},
                { id: 31, text: '64', value: 'mr-64'},
                { id: 32, text: '72', value: 'mr-72'},
                { id: 33, text: '80', value: 'mr-80'},
                { id: 34, text: '96', value: 'mr-96'},
            ]
        },
        bottom: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'mb-0' },
                { id: 2, text: '0.5', value: 'mb-0.5'},
                { id: 3, text: '1', value: 'mb-1'},
                { id: 4, text: '1.5', value: 'mb-1.5'},
                { id: 5, text: '2', value: 'mb-2'},
                { id: 6, text: '2.5', value: 'mb-2.5'},
                { id: 7, text: '3', value: 'mb-3'},
                { id: 8, text: '3.5', value: 'mb-3.5'},
                { id: 9, text: '4', value: 'mb-4'},
                { id: 10, text: '5', value: 'mb-5'},
                { id: 11, text: '6', value: 'mb-6'},
                { id: 12, text: '7', value: 'mb-7'},
                { id: 13, text: '8', value: 'mb-8'},
                { id: 14, text: '9', value: 'mb-9'},
                { id: 15, text: '10', value: 'mb-10'},
                { id: 16, text: '11', value: 'mb-11'},
                { id: 17, text: '12', value: 'mb-12'},
                { id: 18, text: '14', value: 'mb-14'},
                { id: 19, text: '16', value: 'mb-16'},
                { id: 20, text: '20', value: 'mb-20'},
                { id: 21, text: '24', value: 'mb-24'},
                { id: 22, text: '28', value: 'mb-28'},
                { id: 23, text: '32', value: 'mb-32'},
                { id: 24, text: '36', value: 'mb-36'},
                { id: 25, text: '40', value: 'mb-40'},
                { id: 26, text: '44', value: 'mb-44'},
                { id: 27, text: '48', value: 'mb-48'},
                { id: 28, text: '52', value: 'mb-52'},
                { id: 29, text: '56', value: 'mb-56'},
                { id: 30, text: '60', value: 'mb-60'},
                { id: 31, text: '64', value: 'mb-64'},
                { id: 32, text: '72', value: 'mb-72'},
                { id: 33, text: '80', value: 'mb-80'},
                { id: 34, text: '96', value: 'mb-96'},
            ]
        },
        left: {
            regex_pattern: '',
            values: [
                { id: 1, text: '0', value: 'ml-0' },
                { id: 2, text: '0.5', value: 'ml-0.5'},
                { id: 3, text: '1', value: 'ml-1'},
                { id: 4, text: '1.5', value: 'ml-1.5'},
                { id: 5, text: '2', value: 'ml-2'},
                { id: 6, text: '2.5', value: 'ml-2.5'},
                { id: 7, text: '3', value: 'ml-3'},
                { id: 8, text: '3.5', value: 'ml-3.5'},
                { id: 9, text: '4', value: 'ml-4'},
                { id: 10, text: '5', value: 'ml-5'},
                { id: 11, text: '6', value: 'ml-6'},
                { id: 12, text: '7', value: 'ml-7'},
                { id: 13, text: '8', value: 'ml-8'},
                { id: 14, text: '9', value: 'ml-9'},
                { id: 15, text: '10', value: 'ml-10'},
                { id: 16, text: '11', value: 'ml-11'},
                { id: 17, text: '12', value: 'ml-12'},
                { id: 18, text: '14', value: 'ml-14'},
                { id: 19, text: '16', value: 'ml-16'},
                { id: 20, text: '20', value: 'ml-20'},
                { id: 21, text: '24', value: 'ml-24'},
                { id: 22, text: '28', value: 'ml-28'},
                { id: 23, text: '32', value: 'ml-32'},
                { id: 24, text: '36', value: 'ml-36'},
                { id: 25, text: '40', value: 'ml-40'},
                { id: 26, text: '44', value: 'ml-44'},
                { id: 27, text: '48', value: 'ml-48'},
                { id: 28, text: '52', value: 'ml-52'},
                { id: 29, text: '56', value: 'ml-56'},
                { id: 30, text: '60', value: 'ml-60'},
                { id: 31, text: '64', value: 'ml-64'},
                { id: 32, text: '72', value: 'ml-72'},
                { id: 33, text: '80', value: 'ml-80'},
                { id: 34, text: '96', value: 'ml-96'},
            ]
        }
    }
}

export { grid_mapper, flex_mapper, spacing_mapper }
