const grid_mapper = {
    rows: {
        template: {
            regex_pattern: '^grid-(rows-)?([0-9]+)?(\\w+)?$',
            values: [
                { id: 1, text: '1', value: 'grid-rows-1' },
                { id: 2, text: '2', value: 'grid-rows-2' },
                { id: 3, text: '3', value: 'grid-rows-3' },
                { id: 4, text: '4', value: 'grid-rows-4' },
                { id: 5, text: '5', value: 'grid-rows-5' },
                { id: 6, text: '6', value: 'grid-rows-6' },
                { id: 7, text: 'none', value: 'grid-rows-none' },
            ],
        },
        gap: {
            regex_pattern: 'gap-(y-)?[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'gap-y-0' },
                { id: 2, text: '0.125rem', value: 'gap-y-0.5' },
                { id: 3, text: '0.25rem', value: 'gap-y-1' },
                { id: 4, text: '0.375rem', value: 'gap-y-1.5' },
                { id: 5, text: '0.5rem', value: 'gap-y-2' },
                { id: 6, text: '0.625rem', value: 'gap-y-2.5' },
                { id: 7, text: '0.75rem', value: 'gap-y-3' },
                { id: 8, text: '0.875rem', value: 'gap-y-3.5' },
                { id: 9, text: '1rem', value: 'gap-y-4' },
                { id: 10, text: '1.25rem', value: 'gap-y-5' },
                { id: 11, text: '1.5rem', value: 'gap-y-6' },
                { id: 12, text: '1.75rem', value: 'gap-y-7' },
                { id: 13, text: '2rem', value: 'gap-y-8' },
                { id: 14, text: '2.25rem', value: 'gap-y-9' },
                { id: 15, text: '2.5rem', value: 'gap-y-10' },
                { id: 16, text: '2.75rem', value: 'gap-y-11' },
                { id: 17, text: '3rem', value: 'gap-y-12' },
                { id: 18, text: '3.5rem', value: 'gap-y-14' },
                { id: 19, text: '4rem', value: 'gap-y-16' },
                { id: 20, text: '5rem', value: 'gap-y-20' },
                { id: 21, text: '6rem', value: 'gap-y-24' },
                { id: 22, text: '7rem', value: 'gap-y-28' },
                { id: 23, text: '8rem', value: 'gap-y-32' },
                { id: 24, text: '9rem', value: 'gap-y-36' },
                { id: 25, text: '10rem', value: 'gap-y-40' },
                { id: 26, text: '11rem', value: 'gap-y-44' },
                { id: 27, text: '12rem', value: 'gap-y-48' },
                { id: 28, text: '13rem', value: 'gap-y-52' },
                { id: 29, text: '14rem', value: 'gap-y-56' },
                { id: 30, text: '15rem', value: 'gap-y-60' },
                { id: 31, text: '16rem', value: 'gap-y-64' },
                { id: 32, text: '18rem', value: 'gap-y-72' },
                { id: 33, text: '20rem', value: 'gap-y-80' },
                { id: 34, text: '24rem', value: 'gap-y-96' },
            ],
        }
    },
    cols: {
        template: {
            regex_pattern: '^grid-(cols-)?([0-9]+)?(\\w+)?$',
            values: [
                { id: 1, text: '1', value: 'grid-cols-1' },
                { id: 2, text: '2', value: 'grid-cols-2' },
                { id: 3, text: '3', value: 'grid-cols-3' },
                { id: 4, text: '4', value: 'grid-cols-4' },
                { id: 5, text: '5', value: 'grid-cols-5' },
                { id: 6, text: '6', value: 'grid-cols-6' },
                { id: 7, text: '7', value: 'grid-cols-7' },
                { id: 8, text: '8', value: 'grid-cols-8' },
                { id: 9, text: '9', value: 'grid-cols-9' },
                { id: 10, text: '10', value: 'grid-cols-10' },
                { id: 11, text: '11', value: 'grid-cols-11' },
                { id: 12, text: '12', value: 'grid-cols-12' },
                { id: 13, text: 'none', value: 'grid-cols-none' },
            ],
        },
        gap: {
            regex_pattern: 'gap-(x-)?[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'gap-x-0' },
                { id: 2, text: '0.125rem', value: 'gap-x-0.5' },
                { id: 3, text: '0.25rem', value: 'gap-x-1' },
                { id: 4, text: '0.375rem', value: 'gap-x-1.5' },
                { id: 5, text: '0.5rem', value: 'gap-x-2' },
                { id: 6, text: '0.625rem', value: 'gap-x-2.5' },
                { id: 7, text: '0.75rem', value: 'gap-x-3' },
                { id: 8, text: '0.875rem', value: 'gap-x-3.5' },
                { id: 9, text: '1rem', value: 'gap-x-4' },
                { id: 10, text: '1.25rem', value: 'gap-x-5' },
                { id: 11, text: '1.5rem', value: 'gap-x-6' },
                { id: 12, text: '1.75rem', value: 'gap-x-7' },
                { id: 13, text: '2rem', value: 'gap-x-8' },
                { id: 14, text: '2.25rem', value: 'gap-x-9' },
                { id: 15, text: '2.5rem', value: 'gap-x-10' },
                { id: 16, text: '2.75rem', value: 'gap-x-11' },
                { id: 17, text: '3rem', value: 'gap-x-12' },
                { id: 18, text: '3.5rem', value: 'gap-x-14' },
                { id: 19, text: '4rem', value: 'gap-x-16' },
                { id: 20, text: '5rem', value: 'gap-x-20' },
                { id: 21, text: '6rem', value: 'gap-x-24' },
                { id: 22, text: '7rem', value: 'gap-x-28' },
                { id: 23, text: '8rem', value: 'gap-x-32' },
                { id: 24, text: '9rem', value: 'gap-x-36' },
                { id: 25, text: '10rem', value: 'gap-x-40' },
                { id: 26, text: '11rem', value: 'gap-x-44' },
                { id: 27, text: '12rem', value: 'gap-x-48' },
                { id: 28, text: '13rem', value: 'gap-x-52' },
                { id: 29, text: '14rem', value: 'gap-x-56' },
                { id: 30, text: '15rem', value: 'gap-x-60' },
                { id: 31, text: '16rem', value: 'gap-x-64' },
                { id: 32, text: '18rem', value: 'gap-x-72' },
                { id: 33, text: '20rem', value: 'gap-x-80' },
                { id: 34, text: '24rem', value: 'gap-x-96' },
            ]
        }
    }
};

const flex_mapper = {
    gap: {
        regex_pattern: 'gap-(x-)?[0-9]+(\.[0-9])?',
        values: [
            { id: 1, text: '0', value: 'gap-x-0' },
            { id: 2, text: '0.125rem', value: 'gap-x-0.5' },
            { id: 3, text: '0.25rem', value: 'gap-x-1' },
            { id: 4, text: '0.375rem', value: 'gap-x-1.5' },
            { id: 5, text: '0.5rem', value: 'gap-x-2' },
            { id: 6, text: '0.625rem', value: 'gap-x-2.5' },
            { id: 7, text: '0.75rem', value: 'gap-x-3' },
            { id: 8, text: '0.875rem', value: 'gap-x-3.5' },
            { id: 9, text: '1rem', value: 'gap-x-4' },
            { id: 10, text: '1.25rem', value: 'gap-x-5' },
            { id: 11, text: '1.5rem', value: 'gap-x-6' },
            { id: 12, text: '1.75rem', value: 'gap-x-7' },
            { id: 13, text: '2rem', value: 'gap-x-8' },
            { id: 14, text: '2.25rem', value: 'gap-x-9' },
            { id: 15, text: '2.5rem', value: 'gap-x-10' },
            { id: 16, text: '2.75rem', value: 'gap-x-11' },
            { id: 17, text: '3rem', value: 'gap-x-12' },
            { id: 18, text: '3.5rem', value: 'gap-x-14' },
            { id: 19, text: '4rem', value: 'gap-x-16' },
            { id: 20, text: '5rem', value: 'gap-x-20' },
            { id: 21, text: '6rem', value: 'gap-x-24' },
            { id: 22, text: '7rem', value: 'gap-x-28' },
            { id: 23, text: '8rem', value: 'gap-x-32' },
            { id: 24, text: '9rem', value: 'gap-x-36' },
            { id: 25, text: '10rem', value: 'gap-x-40' },
            { id: 26, text: '11rem', value: 'gap-x-44' },
            { id: 27, text: '12rem', value: 'gap-x-48' },
            { id: 28, text: '13rem', value: 'gap-x-52' },
            { id: 29, text: '14rem', value: 'gap-x-56' },
            { id: 30, text: '15rem', value: 'gap-x-60' },
            { id: 31, text: '16rem', value: 'gap-x-64' },
            { id: 32, text: '18rem', value: 'gap-x-72' },
            { id: 33, text: '20rem', value: 'gap-x-80' },
            { id: 34, text: '24rem', value: 'gap-x-96' },
        ]
    }
};

const spacing_mapper = {
    padding: {
        all: {
            regex_pattern: 'p-[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'p-0' },
                { id: 2, text: '0.125rem', value: 'p-0.5' },
                { id: 3, text: '0.25rem', value: 'p-1' },
                { id: 4, text: '0.375rem', value: 'p-1.5' },
                { id: 5, text: '0.5rem', value: 'p-2' },
                { id: 6, text: '0.625rem', value: 'p-2.5' },
                { id: 7, text: '0.75rem', value: 'p-3' },
                { id: 8, text: '0.875rem', value: 'p-3.5' },
                { id: 9, text: '1rem', value: 'p-4' },
                { id: 10, text: '1.25rem', value: 'p-5' },
                { id: 11, text: '1.5rem', value: 'p-6' },
                { id: 12, text: '1.75rem', value: 'p-7' },
                { id: 13, text: '2rem', value: 'p-8' },
                { id: 14, text: '2.25rem', value: 'p-9' },
                { id: 15, text: '2.5rem', value: 'p-10' },
                { id: 16, text: '2.75rem', value: 'p-11' },
                { id: 17, text: '3rem', value: 'p-12' },
                { id: 18, text: '3.5rem', value: 'p-14' },
                { id: 19, text: '4rem', value: 'p-16' },
                { id: 20, text: '5rem', value: 'p-20' },
                { id: 21, text: '6rem', value: 'p-24' },
                { id: 22, text: '7rem', value: 'p-28' },
                { id: 23, text: '8rem', value: 'p-32' },
                { id: 24, text: '9rem', value: 'p-36' },
                { id: 25, text: '10rem', value: 'p-40' },
                { id: 26, text: '11rem', value: 'p-44' },
                { id: 27, text: '12rem', value: 'p-48' },
                { id: 28, text: '13rem', value: 'p-52' },
                { id: 29, text: '14rem', value: 'p-56' },
                { id: 30, text: '15rem', value: 'p-60' },
                { id: 31, text: '16rem', value: 'p-64' },
                { id: 32, text: '18rem', value: 'p-72' },
                { id: 33, text: '20rem', value: 'p-80' },
                { id: 34, text: '24rem', value: 'p-96' },
            ]
        },
        vertical: {
            regex_pattern: 'py-[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'py-0' },
                { id: 2, text: '0.125rem', value: 'py-0.5' },
                { id: 3, text: '0.25rem', value: 'py-1' },
                { id: 4, text: '0.375rem', value: 'py-1.5' },
                { id: 5, text: '0.5rem', value: 'py-2' },
                { id: 6, text: '0.625rem', value: 'py-2.5' },
                { id: 7, text: '0.75rem', value: 'py-3' },
                { id: 8, text: '0.875rem', value: 'py-3.5' },
                { id: 9, text: '1rem', value: 'py-4' },
                { id: 10, text: '1.25rem', value: 'py-5' },
                { id: 11, text: '1.5rem', value: 'py-6' },
                { id: 12, text: '1.75rem', value: 'py-7' },
                { id: 13, text: '2rem', value: 'py-8' },
                { id: 14, text: '2.25rem', value: 'py-9' },
                { id: 15, text: '2.5rem', value: 'py-10' },
                { id: 16, text: '2.75rem', value: 'py-11' },
                { id: 17, text: '3rem', value: 'py-12' },
                { id: 18, text: '3.5rem', value: 'py-14' },
                { id: 19, text: '4rem', value: 'py-16' },
                { id: 20, text: '5rem', value: 'py-20' },
                { id: 21, text: '6rem', value: 'py-24' },
                { id: 22, text: '7rem', value: 'py-28' },
                { id: 23, text: '8rem', value: 'py-32' },
                { id: 24, text: '9rem', value: 'py-36' },
                { id: 25, text: '10rem', value: 'py-40' },
                { id: 26, text: '11rem', value: 'py-44' },
                { id: 27, text: '12rem', value: 'py-48' },
                { id: 28, text: '13rem', value: 'py-52' },
                { id: 29, text: '14rem', value: 'py-56' },
                { id: 30, text: '15rem', value: 'py-60' },
                { id: 31, text: '16rem', value: 'py-64' },
                { id: 32, text: '18rem', value: 'py-72' },
                { id: 33, text: '20rem', value: 'py-80' },
                { id: 34, text: '24rem', value: 'py-96' },
            ]
        },
        horizontal: {
            regex_pattern: 'px-[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'px-0' },
                { id: 2, text: '0.125rem', value: 'px-0.5' },
                { id: 3, text: '0.25rem', value: 'px-1' },
                { id: 4, text: '0.375rem', value: 'px-1.5' },
                { id: 5, text: '0.5rem', value: 'px-2' },
                { id: 6, text: '0.625rem', value: 'px-2.5' },
                { id: 7, text: '0.75rem', value: 'px-3' },
                { id: 8, text: '0.875rem', value: 'px-3.5' },
                { id: 9, text: '1rem', value: 'px-4' },
                { id: 10, text: '1.25rem', value: 'px-5' },
                { id: 11, text: '1.5rem', value: 'px-6' },
                { id: 12, text: '1.75rem', value: 'px-7' },
                { id: 13, text: '2rem', value: 'px-8' },
                { id: 14, text: '2.25rem', value: 'px-9' },
                { id: 15, text: '2.5rem', value: 'px-10' },
                { id: 16, text: '2.75rem', value: 'px-11' },
                { id: 17, text: '3rem', value: 'px-12' },
                { id: 18, text: '3.5rem', value: 'px-14' },
                { id: 19, text: '4rem', value: 'px-16' },
                { id: 20, text: '5rem', value: 'px-20' },
                { id: 21, text: '6rem', value: 'px-24' },
                { id: 22, text: '7rem', value: 'px-28' },
                { id: 23, text: '8rem', value: 'px-32' },
                { id: 24, text: '9rem', value: 'px-36' },
                { id: 25, text: '10rem', value: 'px-40' },
                { id: 26, text: '11rem', value: 'px-44' },
                { id: 27, text: '12rem', value: 'px-48' },
                { id: 28, text: '13rem', value: 'px-52' },
                { id: 29, text: '14rem', value: 'px-56' },
                { id: 30, text: '15rem', value: 'px-60' },
                { id: 31, text: '16rem', value: 'px-64' },
                { id: 32, text: '18rem', value: 'px-72' },
                { id: 33, text: '20rem', value: 'px-80' },
                { id: 34, text: '24rem', value: 'px-96' },
            ]
        },
        top: {
            regex_pattern: 'pt-[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'pt-0' },
                { id: 2, text: '0.125rem', value: 'pt-0.5' },
                { id: 3, text: '0.25rem', value: 'pt-1' },
                { id: 4, text: '0.375rem', value: 'pt-1.5' },
                { id: 5, text: '0.5rem', value: 'pt-2' },
                { id: 6, text: '0.625rem', value: 'pt-2.5' },
                { id: 7, text: '0.75rem', value: 'pt-3' },
                { id: 8, text: '0.875rem', value: 'pt-3.5' },
                { id: 9, text: '1rem', value: 'pt-4' },
                { id: 10, text: '1.25rem', value: 'pt-5' },
                { id: 11, text: '1.5rem', value: 'pt-6' },
                { id: 12, text: '1.75rem', value: 'pt-7' },
                { id: 13, text: '2rem', value: 'pt-8' },
                { id: 14, text: '2.25rem', value: 'pt-9' },
                { id: 15, text: '2.5rem', value: 'pt-10' },
                { id: 16, text: '2.75rem', value: 'pt-11' },
                { id: 17, text: '3rem', value: 'pt-12' },
                { id: 18, text: '3.5rem', value: 'pt-14' },
                { id: 19, text: '4rem', value: 'pt-16' },
                { id: 20, text: '5rem', value: 'pt-20' },
                { id: 21, text: '6rem', value: 'pt-24' },
                { id: 22, text: '7rem', value: 'pt-28' },
                { id: 23, text: '8rem', value: 'pt-32' },
                { id: 24, text: '9rem', value: 'pt-36' },
                { id: 25, text: '10rem', value: 'pt-40' },
                { id: 26, text: '11rem', value: 'pt-44' },
                { id: 27, text: '12rem', value: 'pt-48' },
                { id: 28, text: '13rem', value: 'pt-52' },
                { id: 29, text: '14rem', value: 'pt-56' },
                { id: 30, text: '15rem', value: 'pt-60' },
                { id: 31, text: '16rem', value: 'pt-64' },
                { id: 32, text: '18rem', value: 'pt-72' },
                { id: 33, text: '20rem', value: 'pt-80' },
                { id: 34, text: '24rem', value: 'pt-96' },
            ]
        },
        right: {
            regex_pattern: 'pr-[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'pr-0' },
                { id: 2, text: '0.125rem', value: 'pr-0.5' },
                { id: 3, text: '0.25rem', value: 'pr-1' },
                { id: 4, text: '0.375rem', value: 'pr-1.5' },
                { id: 5, text: '0.5rem', value: 'pr-2' },
                { id: 6, text: '0.625rem', value: 'pr-2.5' },
                { id: 7, text: '0.75rem', value: 'pr-3' },
                { id: 8, text: '0.875rem', value: 'pr-3.5' },
                { id: 9, text: '1rem', value: 'pr-4' },
                { id: 10, text: '1.25rem', value: 'pr-5' },
                { id: 11, text: '1.5rem', value: 'pr-6' },
                { id: 12, text: '1.75rem', value: 'pr-7' },
                { id: 13, text: '2rem', value: 'pr-8' },
                { id: 14, text: '2.25rem', value: 'pr-9' },
                { id: 15, text: '2.5rem', value: 'pr-10' },
                { id: 16, text: '2.75rem', value: 'pr-11' },
                { id: 17, text: '3rem', value: 'pr-12' },
                { id: 18, text: '3.5rem', value: 'pr-14' },
                { id: 19, text: '4rem', value: 'pr-16' },
                { id: 20, text: '5rem', value: 'pr-20' },
                { id: 21, text: '6rem', value: 'pr-24' },
                { id: 22, text: '7rem', value: 'pr-28' },
                { id: 23, text: '8rem', value: 'pr-32' },
                { id: 24, text: '9rem', value: 'pr-36' },
                { id: 25, text: '10rem', value: 'pr-40' },
                { id: 26, text: '11rem', value: 'pr-44' },
                { id: 27, text: '12rem', value: 'pr-48' },
                { id: 28, text: '13rem', value: 'pr-52' },
                { id: 29, text: '14rem', value: 'pr-56' },
                { id: 30, text: '15rem', value: 'pr-60' },
                { id: 31, text: '16rem', value: 'pr-64' },
                { id: 32, text: '18rem', value: 'pr-72' },
                { id: 33, text: '20rem', value: 'pr-80' },
                { id: 34, text: '24rem', value: 'pr-96' },
            ]
        },
        bottom: {
            regex_pattern: 'pb-[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'pb-0' },
                { id: 2, text: '0.125rem', value: 'pb-0.5' },
                { id: 3, text: '0.25rem', value: 'pb-1' },
                { id: 4, text: '0.375rem', value: 'pb-1.5' },
                { id: 5, text: '0.5rem', value: 'pb-2' },
                { id: 6, text: '0.625rem', value: 'pb-2.5' },
                { id: 7, text: '0.75rem', value: 'pb-3' },
                { id: 8, text: '0.875rem', value: 'pb-3.5' },
                { id: 9, text: '1rem', value: 'pb-4' },
                { id: 10, text: '1.25rem', value: 'pb-5' },
                { id: 11, text: '1.5rem', value: 'pb-6' },
                { id: 12, text: '1.75rem', value: 'pb-7' },
                { id: 13, text: '2rem', value: 'pb-8' },
                { id: 14, text: '2.25rem', value: 'pb-9' },
                { id: 15, text: '2.5rem', value: 'pb-10' },
                { id: 16, text: '2.75rem', value: 'pb-11' },
                { id: 17, text: '3rem', value: 'pb-12' },
                { id: 18, text: '3.5rem', value: 'pb-14' },
                { id: 19, text: '4rem', value: 'pb-16' },
                { id: 20, text: '5rem', value: 'pb-20' },
                { id: 21, text: '6rem', value: 'pb-24' },
                { id: 22, text: '7rem', value: 'pb-28' },
                { id: 23, text: '8rem', value: 'pb-32' },
                { id: 24, text: '9rem', value: 'pb-36' },
                { id: 25, text: '10rem', value: 'pb-40' },
                { id: 26, text: '11rem', value: 'pb-44' },
                { id: 27, text: '12rem', value: 'pb-48' },
                { id: 28, text: '13rem', value: 'pb-52' },
                { id: 29, text: '14rem', value: 'pb-56' },
                { id: 30, text: '15rem', value: 'pb-60' },
                { id: 31, text: '16rem', value: 'pb-64' },
                { id: 32, text: '18rem', value: 'pb-72' },
                { id: 33, text: '20rem', value: 'pb-80' },
                { id: 34, text: '24rem', value: 'pb-96' },
            ]
        },
        left: {
            regex_pattern: 'pl-[0-9]+(\.[0-9])?',
            values: [
                { id: 1, text: '0', value: 'pl-0' },
                { id: 2, text: '0.125rem', value: 'pl-0.5' },
                { id: 3, text: '0.25rem', value: 'pl-1' },
                { id: 4, text: '0.375rem', value: 'pl-1.5' },
                { id: 5, text: '0.5rem', value: 'pl-2' },
                { id: 6, text: '0.625rem', value: 'pl-2.5' },
                { id: 7, text: '0.75rem', value: 'pl-3' },
                { id: 8, text: '0.875rem', value: 'pl-3.5' },
                { id: 9, text: '1rem', value: 'pl-4' },
                { id: 10, text: '1.25rem', value: 'pl-5' },
                { id: 11, text: '1.5rem', value: 'pl-6' },
                { id: 12, text: '1.75rem', value: 'pl-7' },
                { id: 13, text: '2rem', value: 'pl-8' },
                { id: 14, text: '2.25rem', value: 'pl-9' },
                { id: 15, text: '2.5rem', value: 'pl-10' },
                { id: 16, text: '2.75rem', value: 'pl-11' },
                { id: 17, text: '3rem', value: 'pl-12' },
                { id: 18, text: '3.5rem', value: 'pl-14' },
                { id: 19, text: '4rem', value: 'pl-16' },
                { id: 20, text: '5rem', value: 'pl-20' },
                { id: 21, text: '6rem', value: 'pl-24' },
                { id: 22, text: '7rem', value: 'pl-28' },
                { id: 23, text: '8rem', value: 'pl-32' },
                { id: 24, text: '9rem', value: 'pl-36' },
                { id: 25, text: '10rem', value: 'pl-40' },
                { id: 26, text: '11rem', value: 'pl-44' },
                { id: 27, text: '12rem', value: 'pl-48' },
                { id: 28, text: '13rem', value: 'pl-52' },
                { id: 29, text: '14rem', value: 'pl-56' },
                { id: 30, text: '15rem', value: 'pl-60' },
                { id: 31, text: '16rem', value: 'pl-64' },
                { id: 32, text: '18rem', value: 'pl-72' },
                { id: 33, text: '20rem', value: 'pl-80' },
                { id: 34, text: '24rem', value: 'pl-96' },
            ]
        }
    },
    margin: {
        all: {
            // regex_pattern: '-?m-[0-9]+(\.[0-9])?',
            regex_pattern: '^-?m-([0-9]+)?(\.[0-9])?(\\w+)?$',
            values: [
                { id: 1, text: '0', value: 'm-0' },
                { id: 2, text: '0.125rem', value: 'm-0.5' },
                { id: 3, text: '0.25rem', value: 'm-1' },
                { id: 4, text: '0.375rem', value: 'm-1.5' },
                { id: 5, text: '0.5rem', value: 'm-2' },
                { id: 6, text: '0.625rem', value: 'm-2.5' },
                { id: 7, text: '0.75rem', value: 'm-3' },
                { id: 8, text: '0.875rem', value: 'm-3.5' },
                { id: 9, text: '1rem', value: 'm-4' },
                { id: 10, text: '1.25rem', value: 'm-5' },
                { id: 11, text: '1.5rem', value: 'm-6' },
                { id: 12, text: '1.75rem', value: 'm-7' },
                { id: 13, text: '2rem', value: 'm-8' },
                { id: 14, text: '2.25rem', value: 'm-9' },
                { id: 15, text: '2.5rem', value: 'm-10' },
                { id: 16, text: '2.75rem', value: 'm-11' },
                { id: 17, text: '3rem', value: 'm-12' },
                { id: 18, text: '3.5rem', value: 'm-14' },
                { id: 19, text: '4rem', value: 'm-16' },
                { id: 20, text: '5rem', value: 'm-20' },
                { id: 21, text: '6rem', value: 'm-24' },
                { id: 22, text: '7rem', value: 'm-28' },
                { id: 23, text: '8rem', value: 'm-32' },
                { id: 24, text: '9rem', value: 'm-36' },
                { id: 25, text: '10rem', value: 'm-40' },
                { id: 26, text: '11rem', value: 'm-44' },
                { id: 27, text: '12rem', value: 'm-48' },
                { id: 28, text: '13rem', value: 'm-52' },
                { id: 29, text: '14rem', value: 'm-56' },
                { id: 30, text: '15rem', value: 'm-60' },
                { id: 31, text: '16rem', value: 'm-64' },
                { id: 32, text: '18rem', value: 'm-72' },
                { id: 33, text: '20rem', value: 'm-80' },
                { id: 34, text: '24rem', value: 'm-96' },
                { id: 35, text: 'auto', value: 'm-auto' },
                { id: 36, text: '-0', value: '-m-0' },
                { id: 37, text: '-0.125rem', value: '-m-0.5' },
                { id: 38, text: '-0.25rem', value: '-m-1' },
                { id: 39, text: '-0.375rem', value: '-m-1.5' },
                { id: 40, text: '-0.5rem', value: '-m-2' },
                { id: 41, text: '-0.625rem', value: '-m-2.5' },
                { id: 42, text: '-0.75rem', value: '-m-3' },
                { id: 43, text: '-0.875rem', value: '-m-3.5' },
                { id: 44, text: '-1rem', value: '-m-4' },
                { id: 45, text: '-1.25rem', value: '-m-5' },
                { id: 46, text: '-1.5rem', value: '-m-6' },
                { id: 47, text: '-1.75rem', value: '-m-7' },
                { id: 48, text: '-2rem', value: '-m-8' },
                { id: 49, text: '-2.25rem', value: '-m-9' },
                { id: 50, text: '-2.5rem', value: '-m-10' },
                { id: 51, text: '-2.75rem', value: '-m-11' },
                { id: 52, text: '-3rem', value: '-m-12' },
                { id: 53, text: '-3.5rem', value: '-m-14' },
                { id: 54, text: '-4rem', value: '-m-16' },
                { id: 55, text: '-5rem', value: '-m-20' },
                { id: 56, text: '-6rem', value: '-m-24' },
                { id: 57, text: '-7rem', value: '-m-28' },
                { id: 58, text: '-8rem', value: '-m-32' },
                { id: 59, text: '-9rem', value: '-m-36' },
                { id: 60, text: '-10rem', value: '-m-40' },
                { id: 61, text: '-11rem', value: '-m-44' },
                { id: 62, text: '-12rem', value: '-m-48' },
                { id: 63, text: '-13rem', value: '-m-52' },
                { id: 64, text: '-14rem', value: '-m-56' },
                { id: 65, text: '-15rem', value: '-m-60' },
                { id: 66, text: '-16rem', value: '-m-64' },
                { id: 67, text: '-18rem', value: '-m-72' },
                { id: 68, text: '-20rem', value: '-m-80' },
                { id: 69, text: '-24rem', value: '-m-96' },
            ]
        },
        vertical: {
            // regex_pattern: 'my-[0-9]+(\.[0-9])?',
            regex_pattern: '^-?my-([0-9]+)?(\.[0-9])?(\\w+)?$',
            values: [
                { id: 1, text: '0', value: 'my-0' },
                { id: 2, text: '0.125rem', value: 'my-0.5' },
                { id: 3, text: '0.25rem', value: 'my-1' },
                { id: 4, text: '0.375rem', value: 'my-1.5' },
                { id: 5, text: '0.5rem', value: 'my-2' },
                { id: 6, text: '0.625rem', value: 'my-2.5' },
                { id: 7, text: '0.75rem', value: 'my-3' },
                { id: 8, text: '0.875rem', value: 'my-3.5' },
                { id: 9, text: '1rem', value: 'my-4' },
                { id: 10, text: '1.25rem', value: 'my-5' },
                { id: 11, text: '1.5rem', value: 'my-6' },
                { id: 12, text: '1.75rem', value: 'my-7' },
                { id: 13, text: '2rem', value: 'my-8' },
                { id: 14, text: '2.25rem', value: 'my-9' },
                { id: 15, text: '2.5rem', value: 'my-10' },
                { id: 16, text: '2.75rem', value: 'my-11' },
                { id: 17, text: '3rem', value: 'my-12' },
                { id: 18, text: '3.5rem', value: 'my-14' },
                { id: 19, text: '4rem', value: 'my-16' },
                { id: 20, text: '5rem', value: 'my-20' },
                { id: 21, text: '6rem', value: 'my-24' },
                { id: 22, text: '7rem', value: 'my-28' },
                { id: 23, text: '8rem', value: 'my-32' },
                { id: 24, text: '9rem', value: 'my-36' },
                { id: 25, text: '10rem', value: 'my-40' },
                { id: 26, text: '11rem', value: 'my-44' },
                { id: 27, text: '12rem', value: 'my-48' },
                { id: 28, text: '13rem', value: 'my-52' },
                { id: 29, text: '14rem', value: 'my-56' },
                { id: 30, text: '15rem', value: 'my-60' },
                { id: 31, text: '16rem', value: 'my-64' },
                { id: 32, text: '18rem', value: 'my-72' },
                { id: 33, text: '20rem', value: 'my-80' },
                { id: 34, text: '24rem', value: 'my-96' },
                { id: 35, text: 'auto', value: 'my-auto' },
                { id: 36, text: '-0', value: '-my-0' },
                { id: 37, text: '-0.125rem', value: '-my-0.5' },
                { id: 38, text: '-0.25rem', value: '-my-1' },
                { id: 39, text: '-0.375rem', value: '-my-1.5' },
                { id: 40, text: '-0.5rem', value: '-my-2' },
                { id: 41, text: '-0.625rem', value: '-my-2.5' },
                { id: 42, text: '-0.75rem', value: '-my-3' },
                { id: 43, text: '-0.875rem', value: '-my-3.5' },
                { id: 44, text: '-1rem', value: '-my-4' },
                { id: 45, text: '-1.25rem', value: '-my-5' },
                { id: 46, text: '-1.5rem', value: '-my-6' },
                { id: 47, text: '-1.75rem', value: '-my-7' },
                { id: 48, text: '-2rem', value: '-my-8' },
                { id: 49, text: '-2.25rem', value: '-my-9' },
                { id: 50, text: '-2.5rem', value: '-my-10' },
                { id: 51, text: '-2.75rem', value: '-my-11' },
                { id: 52, text: '-3rem', value: '-my-12' },
                { id: 53, text: '-3.5rem', value: '-my-14' },
                { id: 54, text: '-4rem', value: '-my-16' },
                { id: 55, text: '-5rem', value: '-my-20' },
                { id: 56, text: '-6rem', value: '-my-24' },
                { id: 57, text: '-7rem', value: '-my-28' },
                { id: 58, text: '-8rem', value: '-my-32' },
                { id: 59, text: '-9rem', value: '-my-36' },
                { id: 60, text: '-10rem', value: '-my-40' },
                { id: 61, text: '-11rem', value: '-my-44' },
                { id: 62, text: '-12rem', value: '-my-48' },
                { id: 63, text: '-13rem', value: '-my-52' },
                { id: 64, text: '-14rem', value: '-my-56' },
                { id: 65, text: '-15rem', value: '-my-60' },
                { id: 66, text: '-16rem', value: '-my-64' },
                { id: 67, text: '-18rem', value: '-my-72' },
                { id: 68, text: '-20rem', value: '-my-80' },
                { id: 69, text: '-24rem', value: '-my-96' },
            ]
        },
        horizontal: {
            // regex_pattern: 'mx-[0-9]+(\.[0-9])?',
            regex_pattern: '^-?mx-([0-9]+)?(\.[0-9])?(\\w+)?$',
            values: [
                { id: 1, text: '0', value: 'mx-0' },
                { id: 2, text: '0.125rem', value: 'mx-0.5' },
                { id: 3, text: '0.25rem', value: 'mx-1' },
                { id: 4, text: '0.375rem', value: 'mx-1.5' },
                { id: 5, text: '0.5rem', value: 'mx-2' },
                { id: 6, text: '0.625rem', value: 'mx-2.5' },
                { id: 7, text: '0.75rem', value: 'mx-3' },
                { id: 8, text: '0.875rem', value: 'mx-3.5' },
                { id: 9, text: '1rem', value: 'mx-4' },
                { id: 10, text: '1.25rem', value: 'mx-5' },
                { id: 11, text: '1.5rem', value: 'mx-6' },
                { id: 12, text: '1.75rem', value: 'mx-7' },
                { id: 13, text: '2rem', value: 'mx-8' },
                { id: 14, text: '2.25rem', value: 'mx-9' },
                { id: 15, text: '2.5rem', value: 'mx-10' },
                { id: 16, text: '2.75rem', value: 'mx-11' },
                { id: 17, text: '3rem', value: 'mx-12' },
                { id: 18, text: '3.5rem', value: 'mx-14' },
                { id: 19, text: '4rem', value: 'mx-16' },
                { id: 20, text: '5rem', value: 'mx-20' },
                { id: 21, text: '6rem', value: 'mx-24' },
                { id: 22, text: '7rem', value: 'mx-28' },
                { id: 23, text: '8rem', value: 'mx-32' },
                { id: 24, text: '9rem', value: 'mx-36' },
                { id: 25, text: '10rem', value: 'mx-40' },
                { id: 26, text: '11rem', value: 'mx-44' },
                { id: 27, text: '12rem', value: 'mx-48' },
                { id: 28, text: '13rem', value: 'mx-52' },
                { id: 29, text: '14rem', value: 'mx-56' },
                { id: 30, text: '15rem', value: 'mx-60' },
                { id: 31, text: '16rem', value: 'mx-64' },
                { id: 32, text: '18rem', value: 'mx-72' },
                { id: 33, text: '20rem', value: 'mx-80' },
                { id: 34, text: '24rem', value: 'mx-96' },
                { id: 35, text: 'auto', value: 'mx-auto' },
                { id: 36, text: '-0', value: '-mx-0' },
                { id: 37, text: '-0.125rem', value: '-mx-0.5' },
                { id: 38, text: '-0.25rem', value: '-mx-1' },
                { id: 39, text: '-0.375rem', value: '-mx-1.5' },
                { id: 40, text: '-0.5rem', value: '-mx-2' },
                { id: 41, text: '-0.625rem', value: '-mx-2.5' },
                { id: 42, text: '-0.75rem', value: '-mx-3' },
                { id: 43, text: '-0.875rem', value: '-mx-3.5' },
                { id: 44, text: '-1rem', value: '-mx-4' },
                { id: 45, text: '-1.25rem', value: '-mx-5' },
                { id: 46, text: '-1.5rem', value: '-mx-6' },
                { id: 47, text: '-1.75rem', value: '-mx-7' },
                { id: 48, text: '-2rem', value: '-mx-8' },
                { id: 49, text: '-2.25rem', value: '-mx-9' },
                { id: 50, text: '-2.5rem', value: '-mx-10' },
                { id: 51, text: '-2.75rem', value: '-mx-11' },
                { id: 52, text: '-3rem', value: '-mx-12' },
                { id: 53, text: '-3.5rem', value: '-mx-14' },
                { id: 54, text: '-4rem', value: '-mx-16' },
                { id: 55, text: '-5rem', value: '-mx-20' },
                { id: 56, text: '-6rem', value: '-mx-24' },
                { id: 57, text: '-7rem', value: '-mx-28' },
                { id: 58, text: '-8rem', value: '-mx-32' },
                { id: 59, text: '-9rem', value: '-mx-36' },
                { id: 60, text: '-10rem', value: '-mx-40' },
                { id: 61, text: '-11rem', value: '-mx-44' },
                { id: 62, text: '-12rem', value: '-mx-48' },
                { id: 63, text: '-13rem', value: '-mx-52' },
                { id: 64, text: '-14rem', value: '-mx-56' },
                { id: 65, text: '-15rem', value: '-mx-60' },
                { id: 66, text: '-16rem', value: '-mx-64' },
                { id: 67, text: '-18rem', value: '-mx-72' },
                { id: 68, text: '-20rem', value: '-mx-80' },
                { id: 69, text: '-24rem', value: '-mx-96' },
            ]
        },
        top: {
            // regex_pattern: 'mt-[0-9]+(\.[0-9])?',
            regex_pattern: '^-?mt-([0-9]+)?(\.[0-9])?(\\w+)?$',
            values: [
                { id: 1, text: '0', value: 'mt-0' },
                { id: 2, text: '0.125rem', value: 'mt-0.5' },
                { id: 3, text: '0.25rem', value: 'mt-1' },
                { id: 4, text: '0.375rem', value: 'mt-1.5' },
                { id: 5, text: '0.5rem', value: 'mt-2' },
                { id: 6, text: '0.625rem', value: 'mt-2.5' },
                { id: 7, text: '0.75rem', value: 'mt-3' },
                { id: 8, text: '0.875rem', value: 'mt-3.5' },
                { id: 9, text: '1rem', value: 'mt-4' },
                { id: 10, text: '1.25rem', value: 'mt-5' },
                { id: 11, text: '1.5rem', value: 'mt-6' },
                { id: 12, text: '1.75rem', value: 'mt-7' },
                { id: 13, text: '2rem', value: 'mt-8' },
                { id: 14, text: '2.25rem', value: 'mt-9' },
                { id: 15, text: '2.5rem', value: 'mt-10' },
                { id: 16, text: '2.75rem', value: 'mt-11' },
                { id: 17, text: '3rem', value: 'mt-12' },
                { id: 18, text: '3.5rem', value: 'mt-14' },
                { id: 19, text: '4rem', value: 'mt-16' },
                { id: 20, text: '5rem', value: 'mt-20' },
                { id: 21, text: '6rem', value: 'mt-24' },
                { id: 22, text: '7rem', value: 'mt-28' },
                { id: 23, text: '8rem', value: 'mt-32' },
                { id: 24, text: '9rem', value: 'mt-36' },
                { id: 25, text: '10rem', value: 'mt-40' },
                { id: 26, text: '11rem', value: 'mt-44' },
                { id: 27, text: '12rem', value: 'mt-48' },
                { id: 28, text: '13rem', value: 'mt-52' },
                { id: 29, text: '14rem', value: 'mt-56' },
                { id: 30, text: '15rem', value: 'mt-60' },
                { id: 31, text: '16rem', value: 'mt-64' },
                { id: 32, text: '18rem', value: 'mt-72' },
                { id: 33, text: '20rem', value: 'mt-80' },
                { id: 34, text: '24rem', value: 'mt-96' },
                { id: 35, text: 'auto', value: 'mt-auto' },
                { id: 36, text: '-0', value: '-mt-0' },
                { id: 37, text: '-0.125rem', value: '-mt-0.5' },
                { id: 38, text: '-0.25rem', value: '-mt-1' },
                { id: 39, text: '-0.375rem', value: '-mt-1.5' },
                { id: 40, text: '-0.5rem', value: '-mt-2' },
                { id: 41, text: '-0.625rem', value: '-mt-2.5' },
                { id: 42, text: '-0.75rem', value: '-mt-3' },
                { id: 43, text: '-0.875rem', value: '-mt-3.5' },
                { id: 44, text: '-1rem', value: '-mt-4' },
                { id: 45, text: '-1.25rem', value: '-mt-5' },
                { id: 46, text: '-1.5rem', value: '-mt-6' },
                { id: 47, text: '-1.75rem', value: '-mt-7' },
                { id: 48, text: '-2rem', value: '-mt-8' },
                { id: 49, text: '-2.25rem', value: '-mt-9' },
                { id: 50, text: '-2.5rem', value: '-mt-10' },
                { id: 51, text: '-2.75rem', value: '-mt-11' },
                { id: 52, text: '-3rem', value: '-mt-12' },
                { id: 53, text: '-3.5rem', value: '-mt-14' },
                { id: 54, text: '-4rem', value: '-mt-16' },
                { id: 55, text: '-5rem', value: '-mt-20' },
                { id: 56, text: '-6rem', value: '-mt-24' },
                { id: 57, text: '-7rem', value: '-mt-28' },
                { id: 58, text: '-8rem', value: '-mt-32' },
                { id: 59, text: '-9rem', value: '-mt-36' },
                { id: 60, text: '-10rem', value: '-mt-40' },
                { id: 61, text: '-11rem', value: '-mt-44' },
                { id: 62, text: '-12rem', value: '-mt-48' },
                { id: 63, text: '-13rem', value: '-mt-52' },
                { id: 64, text: '-14rem', value: '-mt-56' },
                { id: 65, text: '-15rem', value: '-mt-60' },
                { id: 66, text: '-16rem', value: '-mt-64' },
                { id: 67, text: '-18rem', value: '-mt-72' },
                { id: 68, text: '-20rem', value: '-mt-80' },
                { id: 69, text: '-24rem', value: '-mt-96' },
            ]
        },
        right: {
            // regex_pattern: 'mr-[0-9]+(\.[0-9])?',
            regex_pattern: '^-?mr-([0-9]+)?(\.[0-9])?(\\w+)?$',
            values: [
                { id: 1, text: '0', value: 'mr-0' },
                { id: 2, text: '0.125rem', value: 'mr-0.5' },
                { id: 3, text: '0.25rem', value: 'mr-1' },
                { id: 4, text: '0.375rem', value: 'mr-1.5' },
                { id: 5, text: '0.5rem', value: 'mr-2' },
                { id: 6, text: '0.625rem', value: 'mr-2.5' },
                { id: 7, text: '0.75rem', value: 'mr-3' },
                { id: 8, text: '0.875rem', value: 'mr-3.5' },
                { id: 9, text: '1rem', value: 'mr-4' },
                { id: 10, text: '1.25rem', value: 'mr-5' },
                { id: 11, text: '1.5rem', value: 'mr-6' },
                { id: 12, text: '1.75rem', value: 'mr-7' },
                { id: 13, text: '2rem', value: 'mr-8' },
                { id: 14, text: '2.25rem', value: 'mr-9' },
                { id: 15, text: '2.5rem', value: 'mr-10' },
                { id: 16, text: '2.75rem', value: 'mr-11' },
                { id: 17, text: '3rem', value: 'mr-12' },
                { id: 18, text: '3.5rem', value: 'mr-14' },
                { id: 19, text: '4rem', value: 'mr-16' },
                { id: 20, text: '5rem', value: 'mr-20' },
                { id: 21, text: '6rem', value: 'mr-24' },
                { id: 22, text: '7rem', value: 'mr-28' },
                { id: 23, text: '8rem', value: 'mr-32' },
                { id: 24, text: '9rem', value: 'mr-36' },
                { id: 25, text: '10rem', value: 'mr-40' },
                { id: 26, text: '11rem', value: 'mr-44' },
                { id: 27, text: '12rem', value: 'mr-48' },
                { id: 28, text: '13rem', value: 'mr-52' },
                { id: 29, text: '14rem', value: 'mr-56' },
                { id: 30, text: '15rem', value: 'mr-60' },
                { id: 31, text: '16rem', value: 'mr-64' },
                { id: 32, text: '18rem', value: 'mr-72' },
                { id: 33, text: '20rem', value: 'mr-80' },
                { id: 34, text: '24rem', value: 'mr-96' },
                { id: 35, text: 'auto', value: 'mr-auto' },
                { id: 36, text: '-0', value: '-mr-0' },
                { id: 37, text: '-0.125rem', value: '-mr-0.5' },
                { id: 38, text: '-0.25rem', value: '-mr-1' },
                { id: 39, text: '-0.375rem', value: '-mr-1.5' },
                { id: 40, text: '-0.5rem', value: '-mr-2' },
                { id: 41, text: '-0.625rem', value: '-mr-2.5' },
                { id: 42, text: '-0.75rem', value: '-mr-3' },
                { id: 43, text: '-0.875rem', value: '-mr-3.5' },
                { id: 44, text: '-1rem', value: '-mr-4' },
                { id: 45, text: '-1.25rem', value: '-mr-5' },
                { id: 46, text: '-1.5rem', value: '-mr-6' },
                { id: 47, text: '-1.75rem', value: '-mr-7' },
                { id: 48, text: '-2rem', value: '-mr-8' },
                { id: 49, text: '-2.25rem', value: '-mr-9' },
                { id: 50, text: '-2.5rem', value: '-mr-10' },
                { id: 51, text: '-2.75rem', value: '-mr-11' },
                { id: 52, text: '-3rem', value: '-mr-12' },
                { id: 53, text: '-3.5rem', value: '-mr-14' },
                { id: 54, text: '-4rem', value: '-mr-16' },
                { id: 55, text: '-5rem', value: '-mr-20' },
                { id: 56, text: '-6rem', value: '-mr-24' },
                { id: 57, text: '-7rem', value: '-mr-28' },
                { id: 58, text: '-8rem', value: '-mr-32' },
                { id: 59, text: '-9rem', value: '-mr-36' },
                { id: 60, text: '-10rem', value: '-mr-40' },
                { id: 61, text: '-11rem', value: '-mr-44' },
                { id: 62, text: '-12rem', value: '-mr-48' },
                { id: 63, text: '-13rem', value: '-mr-52' },
                { id: 64, text: '-14rem', value: '-mr-56' },
                { id: 65, text: '-15rem', value: '-mr-60' },
                { id: 66, text: '-16rem', value: '-mr-64' },
                { id: 67, text: '-18rem', value: '-mr-72' },
                { id: 68, text: '-20rem', value: '-mr-80' },
                { id: 69, text: '-24rem', value: '-mr-96' },
            ]
        },
        bottom: {
            // regex_pattern: 'mb-[0-9]+(\.[0-9])?',
            regex_pattern: '^-?mb-([0-9]+)?(\.[0-9])?(\\w+)?$',
            values: [
                { id: 1, text: '0', value: 'mb-0' },
                { id: 2, text: '0.125rem', value: 'mb-0.5' },
                { id: 3, text: '0.25rem', value: 'mb-1' },
                { id: 4, text: '0.375rem', value: 'mb-1.5' },
                { id: 5, text: '0.5rem', value: 'mb-2' },
                { id: 6, text: '0.625rem', value: 'mb-2.5' },
                { id: 7, text: '0.75rem', value: 'mb-3' },
                { id: 8, text: '0.875rem', value: 'mb-3.5' },
                { id: 9, text: '1rem', value: 'mb-4' },
                { id: 10, text: '1.25rem', value: 'mb-5' },
                { id: 11, text: '1.5rem', value: 'mb-6' },
                { id: 12, text: '1.75rem', value: 'mb-7' },
                { id: 13, text: '2rem', value: 'mb-8' },
                { id: 14, text: '2.25rem', value: 'mb-9' },
                { id: 15, text: '2.5rem', value: 'mb-10' },
                { id: 16, text: '2.75rem', value: 'mb-11' },
                { id: 17, text: '3rem', value: 'mb-12' },
                { id: 18, text: '3.5rem', value: 'mb-14' },
                { id: 19, text: '4rem', value: 'mb-16' },
                { id: 20, text: '5rem', value: 'mb-20' },
                { id: 21, text: '6rem', value: 'mb-24' },
                { id: 22, text: '7rem', value: 'mb-28' },
                { id: 23, text: '8rem', value: 'mb-32' },
                { id: 24, text: '9rem', value: 'mb-36' },
                { id: 25, text: '10rem', value: 'mb-40' },
                { id: 26, text: '11rem', value: 'mb-44' },
                { id: 27, text: '12rem', value: 'mb-48' },
                { id: 28, text: '13rem', value: 'mb-52' },
                { id: 29, text: '14rem', value: 'mb-56' },
                { id: 30, text: '15rem', value: 'mb-60' },
                { id: 31, text: '16rem', value: 'mb-64' },
                { id: 32, text: '18rem', value: 'mb-72' },
                { id: 33, text: '20rem', value: 'mb-80' },
                { id: 34, text: '24rem', value: 'mb-96' },
                { id: 35, text: 'auto', value: 'mb-auto' },
                { id: 36, text: '-0', value: '-mb-0' },
                { id: 37, text: '-0.125rem', value: '-mb-0.5' },
                { id: 38, text: '-0.25rem', value: '-mb-1' },
                { id: 39, text: '-0.375rem', value: '-mb-1.5' },
                { id: 40, text: '-0.5rem', value: '-mb-2' },
                { id: 41, text: '-0.625rem', value: '-mb-2.5' },
                { id: 42, text: '-0.75rem', value: '-mb-3' },
                { id: 43, text: '-0.875rem', value: '-mb-3.5' },
                { id: 44, text: '-1rem', value: '-mb-4' },
                { id: 45, text: '-1.25rem', value: '-mb-5' },
                { id: 46, text: '-1.5rem', value: '-mb-6' },
                { id: 47, text: '-1.75rem', value: '-mb-7' },
                { id: 48, text: '-2rem', value: '-mb-8' },
                { id: 49, text: '-2.25rem', value: '-mb-9' },
                { id: 50, text: '-2.5rem', value: '-mb-10' },
                { id: 51, text: '-2.75rem', value: '-mb-11' },
                { id: 52, text: '-3rem', value: '-mb-12' },
                { id: 53, text: '-3.5rem', value: '-mb-14' },
                { id: 54, text: '-4rem', value: '-mb-16' },
                { id: 55, text: '-5rem', value: '-mb-20' },
                { id: 56, text: '-6rem', value: '-mb-24' },
                { id: 57, text: '-7rem', value: '-mb-28' },
                { id: 58, text: '-8rem', value: '-mb-32' },
                { id: 59, text: '-9rem', value: '-mb-36' },
                { id: 60, text: '-10rem', value: '-mb-40' },
                { id: 61, text: '-11rem', value: '-mb-44' },
                { id: 62, text: '-12rem', value: '-mb-48' },
                { id: 63, text: '-13rem', value: '-mb-52' },
                { id: 64, text: '-14rem', value: '-mb-56' },
                { id: 65, text: '-15rem', value: '-mb-60' },
                { id: 66, text: '-16rem', value: '-mb-64' },
                { id: 67, text: '-18rem', value: '-mb-72' },
                { id: 68, text: '-20rem', value: '-mb-80' },
                { id: 69, text: '-24rem', value: '-mb-96' },
            ]
        },
        left: {
            // regex_pattern: 'ml-[0-9]+(\.[0-9])?',
            regex_pattern: '^-?ml-([0-9]+)?(\.[0-9])?(\\w+)?$',
            values: [
                { id: 1, text: '0', value: 'ml-0' },
                { id: 2, text: '0.125rem', value: 'ml-0.5' },
                { id: 3, text: '0.25rem', value: 'ml-1' },
                { id: 4, text: '0.375rem', value: 'ml-1.5' },
                { id: 5, text: '0.5rem', value: 'ml-2' },
                { id: 6, text: '0.625rem', value: 'ml-2.5' },
                { id: 7, text: '0.75rem', value: 'ml-3' },
                { id: 8, text: '0.875rem', value: 'ml-3.5' },
                { id: 9, text: '1rem', value: 'ml-4' },
                { id: 10, text: '1.25rem', value: 'ml-5' },
                { id: 11, text: '1.5rem', value: 'ml-6' },
                { id: 12, text: '1.75rem', value: 'ml-7' },
                { id: 13, text: '2rem', value: 'ml-8' },
                { id: 14, text: '2.25rem', value: 'ml-9' },
                { id: 15, text: '2.5rem', value: 'ml-10' },
                { id: 16, text: '2.75rem', value: 'ml-11' },
                { id: 17, text: '3rem', value: 'ml-12' },
                { id: 18, text: '3.5rem', value: 'ml-14' },
                { id: 19, text: '4rem', value: 'ml-16' },
                { id: 20, text: '5rem', value: 'ml-20' },
                { id: 21, text: '6rem', value: 'ml-24' },
                { id: 22, text: '7rem', value: 'ml-28' },
                { id: 23, text: '8rem', value: 'ml-32' },
                { id: 24, text: '9rem', value: 'ml-36' },
                { id: 25, text: '10rem', value: 'ml-40' },
                { id: 26, text: '11rem', value: 'ml-44' },
                { id: 27, text: '12rem', value: 'ml-48' },
                { id: 28, text: '13rem', value: 'ml-52' },
                { id: 29, text: '14rem', value: 'ml-56' },
                { id: 30, text: '15rem', value: 'ml-60' },
                { id: 31, text: '16rem', value: 'ml-64' },
                { id: 32, text: '18rem', value: 'ml-72' },
                { id: 33, text: '20rem', value: 'ml-80' },
                { id: 34, text: '24rem', value: 'ml-96' },
                { id: 35, text: 'auto', value: 'ml-auto' },
                { id: 36, text: '-0', value: '-ml-0' },
                { id: 37, text: '-0.125rem', value: '-ml-0.5' },
                { id: 38, text: '-0.25rem', value: '-ml-1' },
                { id: 39, text: '-0.375rem', value: '-ml-1.5' },
                { id: 40, text: '-0.5rem', value: '-ml-2' },
                { id: 41, text: '-0.625rem', value: '-ml-2.5' },
                { id: 42, text: '-0.75rem', value: '-ml-3' },
                { id: 43, text: '-0.875rem', value: '-ml-3.5' },
                { id: 44, text: '-1rem', value: '-ml-4' },
                { id: 45, text: '-1.25rem', value: '-ml-5' },
                { id: 46, text: '-1.5rem', value: '-ml-6' },
                { id: 47, text: '-1.75rem', value: '-ml-7' },
                { id: 48, text: '-2rem', value: '-ml-8' },
                { id: 49, text: '-2.25rem', value: '-ml-9' },
                { id: 50, text: '-2.5rem', value: '-ml-10' },
                { id: 51, text: '-2.75rem', value: '-ml-11' },
                { id: 52, text: '-3rem', value: '-ml-12' },
                { id: 53, text: '-3.5rem', value: '-ml-14' },
                { id: 54, text: '-4rem', value: '-ml-16' },
                { id: 55, text: '-5rem', value: '-ml-20' },
                { id: 56, text: '-6rem', value: '-ml-24' },
                { id: 57, text: '-7rem', value: '-ml-28' },
                { id: 58, text: '-8rem', value: '-ml-32' },
                { id: 59, text: '-9rem', value: '-ml-36' },
                { id: 60, text: '-10rem', value: '-ml-40' },
                { id: 61, text: '-11rem', value: '-ml-44' },
                { id: 62, text: '-12rem', value: '-ml-48' },
                { id: 63, text: '-13rem', value: '-ml-52' },
                { id: 64, text: '-14rem', value: '-ml-56' },
                { id: 65, text: '-15rem', value: '-ml-60' },
                { id: 66, text: '-16rem', value: '-ml-64' },
                { id: 67, text: '-18rem', value: '-ml-72' },
                { id: 68, text: '-20rem', value: '-ml-80' },
                { id: 69, text: '-24rem', value: '-ml-96' },
            ]
        }
    }
};

const sizing_mapper = {
    width: {
        regex_pattern: '^-?w-([0-9]+)?(\/[0-9]+)?(\.[0-9])?(\\w+)?$',
        values: [
            { id: 1, text: '0', value: 'w-0' },
            { id: 2, text: '0.125rem', value: 'w-0.5' },
            { id: 3, text: '0.25rem', value: 'w-1' },
            { id: 4, text: '0.375rem', value: 'w-1.5' },
            { id: 5, text: '0.5rem', value: 'w-2' },
            { id: 6, text: '0.625rem', value: 'w-2.5' },
            { id: 7, text: '0.75rem', value: 'w-3' },
            { id: 8, text: '0.875rem', value: 'w-3.5' },
            { id: 9, text: '1rem', value: 'w-4' },
            { id: 10, text: '1.25rem', value: 'w-5' },
            { id: 11, text: '1.5rem', value: 'w-6' },
            { id: 12, text: '1.75rem', value: 'w-7' },
            { id: 13, text: '2rem', value: 'w-8' },
            { id: 14, text: '2.25rem', value: 'w-9' },
            { id: 15, text: '2.5rem', value: 'w-10' },
            { id: 16, text: '2.75rem', value: 'w-11' },
            { id: 17, text: '3rem', value: 'w-12' },
            { id: 18, text: '3.5rem', value: 'w-14' },
            { id: 19, text: '4rem', value: 'w-16' },
            { id: 20, text: '5rem', value: 'w-20' },
            { id: 21, text: '6rem', value: 'w-24' },
            { id: 22, text: '7rem', value: 'w-28' },
            { id: 23, text: '8rem', value: 'w-32' },
            { id: 24, text: '9rem', value: 'w-36' },
            { id: 25, text: '10rem', value: 'w-40' },
            { id: 26, text: '11rem', value: 'w-44' },
            { id: 27, text: '12rem', value: 'w-48' },
            { id: 28, text: '13rem', value: 'w-52' },
            { id: 29, text: '14rem', value: 'w-56' },
            { id: 30, text: '15rem', value: 'w-60' },
            { id: 31, text: '16rem', value: 'w-64' },
            { id: 32, text: '18rem', value: 'w-72' },
            { id: 33, text: '20rem', value: 'w-80' },
            { id: 34, text: '24rem', value: 'w-96' },
            { id: 35, text: '8.333333%', value: 'w-1/12' },
            { id: 36, text: '16.666667%', value: 'w-1/6' },
            { id: 37, text: '20%', value: 'w-1/5' },
            { id: 38, text: '25%', value: 'w-1/4' },
            { id: 39, text: '33.333333%', value: 'w-1/3' },
            { id: 40, text: '40%', value: 'w-2/5' },
            { id: 41, text: '41.666667%', value: 'w-5/12' },
            { id: 42, text: '50%', value: 'w-1/2' },
            { id: 43, text: '58.333333%', value: 'w-7/12' },
            { id: 44, text: '60%', value: 'w-3/5' },
            { id: 45, text: '66.666666%', value: 'w-2/3' },
            { id: 46, text: '75%', value: 'w-3/4' },
            { id: 47, text: '80%', value: 'w-4/5' },
            { id: 48, text: '83.333333%', value: 'w-5/6' },
            { id: 49, text: '91.666667%', value: 'w-11/12' },
            { id: 50, text: 'auto', value: 'w-auto' },
            { id: 51, text: '100%', value: 'w-full' },
            { id: 52, text: '100vw', value: 'w-screen' },
            { id: 53, text: 'min-content', value: 'w-min' },
            { id: 54, text: 'max-content', value: 'w-max' },
        ]
    },
    height: {
        regex_pattern: '^-?h-([0-9]+)?(\/[0-9]+)?(\.[0-9])?(\\w+)?$',
        values: [
            { id: 1, text: '0', value: 'h-0' },
            { id: 2, text: '0.125rem', value: 'h-0.5' },
            { id: 3, text: '0.25rem', value: 'h-1' },
            { id: 4, text: '0.375rem', value: 'h-1.5' },
            { id: 5, text: '0.5rem', value: 'h-2' },
            { id: 6, text: '0.625rem', value: 'h-2.5' },
            { id: 7, text: '0.75rem', value: 'h-3' },
            { id: 8, text: '0.875rem', value: 'h-3.5' },
            { id: 9, text: '1rem', value: 'h-4' },
            { id: 10, text: '1.25rem', value: 'h-5' },
            { id: 11, text: '1.5rem', value: 'h-6' },
            { id: 12, text: '1.75rem', value: 'h-7' },
            { id: 13, text: '2rem', value: 'h-8' },
            { id: 14, text: '2.25rem', value: 'h-9' },
            { id: 15, text: '2.5rem', value: 'h-10' },
            { id: 16, text: '2.75rem', value: 'h-11' },
            { id: 17, text: '3rem', value: 'h-12' },
            { id: 18, text: '3.5rem', value: 'h-14' },
            { id: 19, text: '4rem', value: 'h-16' },
            { id: 20, text: '5rem', value: 'h-20' },
            { id: 21, text: '6rem', value: 'h-24' },
            { id: 22, text: '7rem', value: 'h-28' },
            { id: 23, text: '8rem', value: 'h-32' },
            { id: 24, text: '9rem', value: 'h-36' },
            { id: 25, text: '10rem', value: 'h-40' },
            { id: 26, text: '11rem', value: 'h-44' },
            { id: 27, text: '12rem', value: 'h-48' },
            { id: 28, text: '13rem', value: 'h-52' },
            { id: 29, text: '14rem', value: 'h-56' },
            { id: 30, text: '15rem', value: 'h-60' },
            { id: 31, text: '16rem', value: 'h-64' },
            { id: 32, text: '18rem', value: 'h-72' },
            { id: 33, text: '20rem', value: 'h-80' },
            { id: 34, text: '24rem', value: 'h-96' },
            { id: 35, text: '8.333333%', value: 'h-1/12' },
            { id: 36, text: '16.666667%', value: 'h-1/6' },
            { id: 37, text: '20%', value: 'h-1/5' },
            { id: 38, text: '25%', value: 'h-1/4' },
            { id: 39, text: '33.333333%', value: 'h-1/3' },
            { id: 40, text: '40%', value: 'h-2/5' },
            { id: 41, text: '41.666667%', value: 'h-5/12' },
            { id: 42, text: '50%', value: 'h-1/2' },
            { id: 43, text: '58.333333%', value: 'h-7/12' },
            { id: 44, text: '60%', value: 'h-3/5' },
            { id: 45, text: '66.666666%', value: 'h-2/3' },
            { id: 46, text: '75%', value: 'h-3/4' },
            { id: 47, text: '80%', value: 'h-4/5' },
            { id: 48, text: '83.333333%', value: 'h-5/6' },
            { id: 49, text: '91.666667%', value: 'h-11/12' },
            { id: 50, text: 'auto', value: 'h-auto' },
            { id: 51, text: '100%', value: 'h-full' },
            { id: 52, text: '100vh', value: 'h-screen' },
        ]
    }
};

const whitespace_mapper = {
    regex_pattern: '^whitespace-\\w+(-\\w+)?$',
    values: [
        { id: 1, text: 'normal', value: 'whitespace-normal' },
        { id: 2, text: 'nowrap', value: 'whitespace-nowrap' },
        { id: 3, text: 'pre', value: 'whitespace-pre' },
        { id: 4, text: 'pre-line', value: 'whitespace-pre-line' },
        { id: 5, text: 'pre-wrap', value: 'whitespace-pre-wrap' },
    ]
};

const overflow_mapper = {
    regex_pattern: '^overflow-([xy]-)?(\\w+)?$',
    values: [
        { id: 1, text: 'auto', value: 'overflow-auto' },
        { id: 2, text: 'hidden', value: 'overflow-hidden' },
        { id: 2, text: 'visible', value: 'overflow-visible' },
        { id: 2, text: 'scroll', value: 'overflow-scroll' },
        { id: 2, text: 'x-auto', value: 'overflow-x-auto' },
        { id: 2, text: 'y-auto', value: 'overflow-y-auto' },
        { id: 2, text: 'x-hidden', value: 'overflow-x-hidden' },
        { id: 2, text: 'y-hidden', value: 'overflow-y-hidden' },
        { id: 2, text: 'x-visible', value: 'overflow-x-visible' },
        { id: 2, text: 'y-visible', value: 'overflow-y-visible' },
        { id: 2, text: 'x-scroll', value: 'overflow-x-scroll' },
        { id: 2, text: 'y-scroll', value: 'overflow-y-scroll' },
    ]
};

export { grid_mapper, flex_mapper, spacing_mapper, sizing_mapper, whitespace_mapper, overflow_mapper }
